version: "3.6"

services:
  rstudio:
    image: rocker/rstudio:4.0.3
    container_name: rstudio
    restart: on-failure
    volumes:
      - type: volume
        source: rstudio
        target: /home/rstudio
        volume:
          no-copy: true
      - type: bind
        source: ./projects
        target: /home/rstudio/projects
      - type: volume
        source: r_libs
        target: /usr/local/lib/R
        volume:
          no-copy: true
    networks:
      - net
    environment:
      - PASSWORD=rstudio
    expose:
      - 8787

networks:
  tki-net:
    name: net

volumes:
  r_libs:
  rstudio:
