--- 
title: "Técnicas cuantitativas"
author: "Enric Aguilar y Benito Zaragozí"
date: "`r format(Sys.time(), '%d-%b-%Y')`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Este documento forma parte de los materiales para la asignatura 'Técnicas cuantitativas' del Máster universitario en planificación, gobernanza y liderazgo territorial"
always_allow_html: true
---

# Antes de empezar
En este breve capítulo explicamos los aspectos básicos para que podáis reproducir los ejercicios y entregar las actividades utilizando Markdown y Rstudio. Aquí planteamos los conceptos básicos para preparar un documento que incluye explicaciónes, código y los resultados de análisis R. Se trata de una estratégia de **programación literaria**.

## Prerrequisitos
Para preparar cualquier tarea en este formato es necesario instalar primero R y RStudio con los paquetes `knitr` y `rmarkdown`.

## Tipos de ficheros

- Los archivos para producir documentos de RMarkdown tienen la extensión `.Rmd`.
- Los archivos deben abrirse con RStudio y se compilan haciendo clic en el botón knitr.
- El resultado es un documento en formato `.pdf`, `.html` o `.doc`.

## Un ejemplo muy sencillo

Cread un fichero con el siguiente contenido

```
Hola, soy **R Markdown**

Aprende más sobre mi [aquí](http://rmarkdown.rstudio.com/).
```

al hacer clic en el botón `knitr a HTML` de Rstudio se crea un archivo `.html` con este contenido.


## Estructura básica de un documento Markdown
Revisemos las partes más importantes del documento `Rmd`.

### Cabecera
La cabecera está en la parte superior del documento dentro de estas dos líneas `---`

```
---
title: "Write your title here"
author: "Write your name here"
date: "Write the date here"
output:
  pdf_document: default
  html_document: default
  word_document: default
---
```

En el encabezado del archivo debe escribir el título del documento, su nombre y la fecha. La declaración de salida se utiliza para la clase del documento final, `pdf`, `html`o `doc`. Para producir un PDF es necesario tener instalado un motor de LaTeX.

### Insertar código R
A continuación, configuramos las opciones necesarias para imprimir el código R y la salida R en el documento final.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

La primera línea es ocultar este fragmento de código en el documento final.

La segunda línea es para imprimir el código R y la salida R en el documento final. 

### Formatos de texto
El texto sin formato se escribe como en cualquier otro documento, como un documento de Word. Debe tener cuidado con las letras en cursiva o negrita y algunos caracteres especiales. Por ejemplo

- **Negrita**: escriba el texto entre \*\*Negrita\*\* o \_\_Negrita\_\_
- *Cursiva*: escriba su texto entre\*cursiva\* o \_Italica\_
- Encabezados de sección

```
# Título 1
## Título 2
### Título 3
```

Cuantos más símbolos \# escriba antes de su texto, menor será el tamaño de su título

Puede encontrar más información sobre cómo escribir en el siguiente [archivo](https://rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf).

### Generando el documento

Para compilar el archivo `.Rmd` y obtener su documento final, simplemente haga clic en el botón `Knit` y seleccione `Knit a PDF` para producir un archivo `.pdf`.
