<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 3 Estadística inferencial | Técnicas cuantitativas</title>
  <meta name="description" content="Este documento forma parte de los materiales para la asignatura ‘Técnicas cuantitativas’ del Máster universitario en planificación, gobernanza y liderazgo territorial" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 3 Estadística inferencial | Técnicas cuantitativas" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Este documento forma parte de los materiales para la asignatura ‘Técnicas cuantitativas’ del Máster universitario en planificación, gobernanza y liderazgo territorial" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 3 Estadística inferencial | Técnicas cuantitativas" />
  
  <meta name="twitter:description" content="Este documento forma parte de los materiales para la asignatura ‘Técnicas cuantitativas’ del Máster universitario en planificación, gobernanza y liderazgo territorial" />
  

<meta name="author" content="Enric Aguilar y Benito Zaragozí" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="estadística-descriptiva.html"/>
<link rel="next" href="el-muestreo-estadístico.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script src="libs/htmlwidgets-1.5.2/htmlwidgets.js"></script>
<script src="libs/d3-3.3.8/d3.min.js"></script>
<script src="libs/dagre-0.4.0/dagre-d3.min.js"></script>
<link href="libs/mermaid-0.3.0/dist/mermaid.css" rel="stylesheet" />
<script src="libs/mermaid-0.3.0/dist/mermaid.slim.min.js"></script>
<link href="libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet" />
<script src="libs/chromatography-0.1/chromatography.js"></script>
<script src="libs/DiagrammeR-binding-1.0.6.1/DiagrammeR.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Técnicas cuantitativas</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Antes de empezar</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#prerrequisitos"><i class="fa fa-check"></i><b>0.1</b> Prerrequisitos</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#tipos-de-ficheros"><i class="fa fa-check"></i><b>0.2</b> Tipos de ficheros</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#un-ejemplo-muy-sencillo"><i class="fa fa-check"></i><b>0.3</b> Un ejemplo muy sencillo</a></li>
<li class="chapter" data-level="0.4" data-path="index.html"><a href="index.html#estructura-básica-de-un-documento-markdown"><i class="fa fa-check"></i><b>0.4</b> Estructura básica de un documento Markdown</a><ul>
<li class="chapter" data-level="0.4.1" data-path="index.html"><a href="index.html#cabecera"><i class="fa fa-check"></i><b>0.4.1</b> Cabecera</a></li>
<li class="chapter" data-level="0.4.2" data-path="index.html"><a href="index.html#insertar-código-r"><i class="fa fa-check"></i><b>0.4.2</b> Insertar código R</a></li>
<li class="chapter" data-level="0.4.3" data-path="index.html"><a href="index.html#formatos-de-texto"><i class="fa fa-check"></i><b>0.4.3</b> Formatos de texto</a></li>
<li class="chapter" data-level="0.4.4" data-path="index.html"><a href="index.html#generando-el-documento"><i class="fa fa-check"></i><b>0.4.4</b> Generando el documento</a></li>
</ul></li>
<li class="chapter" data-level="0.5" data-path="index.html"><a href="index.html#ejercicio"><i class="fa fa-check"></i><b>0.5</b> Ejercicio</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introducción</a><ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#r-como-lenguaje-de-programación"><i class="fa fa-check"></i><b>1.1</b> R como lenguaje de programación</a></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#utilizando-rstudio"><i class="fa fa-check"></i><b>1.2</b> Utilizando RStudio</a></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#interpretación-de-valores"><i class="fa fa-check"></i><b>1.3</b> Interpretación de valores</a></li>
<li class="chapter" data-level="1.4" data-path="intro.html"><a href="intro.html#variables"><i class="fa fa-check"></i><b>1.4</b> Variables</a></li>
<li class="chapter" data-level="1.5" data-path="intro.html"><a href="intro.html#tipos-basicos"><i class="fa fa-check"></i><b>1.5</b> Tipos basicos</a><ul>
<li class="chapter" data-level="1.5.1" data-path="intro.html"><a href="intro.html#números"><i class="fa fa-check"></i><b>1.5.1</b> Números</a></li>
<li class="chapter" data-level="1.5.2" data-path="intro.html"><a href="intro.html#lógicos-o-booleanos"><i class="fa fa-check"></i><b>1.5.2</b> Lógicos o booleanos</a></li>
<li class="chapter" data-level="1.5.3" data-path="intro.html"><a href="intro.html#cádenas-de-caracteres"><i class="fa fa-check"></i><b>1.5.3</b> Cádenas de caracteres</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="intro.html"><a href="intro.html#estructuras-de-datos"><i class="fa fa-check"></i><b>1.6</b> Estructuras de datos</a><ul>
<li class="chapter" data-level="1.6.1" data-path="intro.html"><a href="intro.html#vectores"><i class="fa fa-check"></i><b>1.6.1</b> Vectores</a></li>
<li class="chapter" data-level="1.6.2" data-path="intro.html"><a href="intro.html#listas"><i class="fa fa-check"></i><b>1.6.2</b> Listas</a></li>
<li class="chapter" data-level="1.6.3" data-path="intro.html"><a href="intro.html#matrices"><i class="fa fa-check"></i><b>1.6.3</b> Matrices</a></li>
<li class="chapter" data-level="1.6.4" data-path="intro.html"><a href="intro.html#data-frames"><i class="fa fa-check"></i><b>1.6.4</b> Data frames</a></li>
<li class="chapter" data-level="1.6.5" data-path="intro.html"><a href="intro.html#factores"><i class="fa fa-check"></i><b>1.6.5</b> Factores</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="intro.html"><a href="intro.html#funciones"><i class="fa fa-check"></i><b>1.7</b> Funciones</a></li>
<li class="chapter" data-level="1.8" data-path="intro.html"><a href="intro.html#tidyverse"><i class="fa fa-check"></i><b>1.8</b> Tidyverse</a><ul>
<li class="chapter" data-level="1.8.1" data-path="intro.html"><a href="intro.html#stringr"><i class="fa fa-check"></i><b>1.8.1</b> stringr</a></li>
<li class="chapter" data-level="1.8.2" data-path="intro.html"><a href="intro.html#el-operador-pipe"><i class="fa fa-check"></i><b>1.8.2</b> El operador <code>pipe</code></a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="intro.html"><a href="intro.html#ejercicios"><i class="fa fa-check"></i><b>1.9</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html"><i class="fa fa-check"></i><b>2</b> Estadística descriptiva</a><ul>
<li class="chapter" data-level="2.1" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#tendencia-central"><i class="fa fa-check"></i><b>2.1</b> Tendencia central</a><ul>
<li class="chapter" data-level="2.1.1" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#mínimo-y-máximo"><i class="fa fa-check"></i><b>2.1.1</b> Mínimo y máximo</a></li>
<li class="chapter" data-level="2.1.2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#media"><i class="fa fa-check"></i><b>2.1.2</b> Media</a></li>
<li class="chapter" data-level="2.1.3" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#mediana"><i class="fa fa-check"></i><b>2.1.3</b> Mediana</a></li>
<li class="chapter" data-level="2.1.4" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#primer-y-tercer-cuartil"><i class="fa fa-check"></i><b>2.1.4</b> Primer y tercer cuartil</a></li>
<li class="chapter" data-level="2.1.5" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#moda"><i class="fa fa-check"></i><b>2.1.5</b> Moda</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#dispersión"><i class="fa fa-check"></i><b>2.2</b> Dispersión</a><ul>
<li class="chapter" data-level="2.2.1" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#rango"><i class="fa fa-check"></i><b>2.2.1</b> Rango</a></li>
<li class="chapter" data-level="2.2.2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#desviación-estándard"><i class="fa fa-check"></i><b>2.2.2</b> Desviación estándard</a></li>
<li class="chapter" data-level="2.2.3" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#varianza"><i class="fa fa-check"></i><b>2.2.3</b> Varianza</a></li>
<li class="chapter" data-level="2.2.4" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#coeficiente-de-variación"><i class="fa fa-check"></i><b>2.2.4</b> Coeficiente de variación</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#correlación"><i class="fa fa-check"></i><b>2.3</b> Correlación</a><ul>
<li class="chapter" data-level="2.3.1" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#datos"><i class="fa fa-check"></i><b>2.3.1</b> Datos</a></li>
<li class="chapter" data-level="2.3.2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#coeficiente-de-correlación"><i class="fa fa-check"></i><b>2.3.2</b> Coeficiente de correlación</a></li>
<li class="chapter" data-level="2.3.3" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#test-de-correlación"><i class="fa fa-check"></i><b>2.3.3</b> Test de correlación</a></li>
<li class="chapter" data-level="2.3.4" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#visualizando-correlaciones"><i class="fa fa-check"></i><b>2.3.4</b> Visualizando correlaciones</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="intro.html"><a href="intro.html#ejercicios"><i class="fa fa-check"></i><b>2.4</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html"><i class="fa fa-check"></i><b>3</b> Estadística inferencial</a><ul>
<li class="chapter" data-level="3.1" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#distribuciones-de-probabilidad"><i class="fa fa-check"></i><b>3.1</b> Distribuciones de probabilidad</a><ul>
<li class="chapter" data-level="3.1.1" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#funciones-de-r-para-distribuciones-de-probabilidad"><i class="fa fa-check"></i><b>3.1.1</b> Funciones de R para distribuciones de probabilidad</a></li>
<li class="chapter" data-level="3.1.2" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#la-distribución-binomial"><i class="fa fa-check"></i><b>3.1.2</b> La distribución binomial</a></li>
<li class="chapter" data-level="3.1.3" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#la-distribución-normal"><i class="fa fa-check"></i><b>3.1.3</b> La distribución normal</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#introduccion-a-los-test-de-hipótesis"><i class="fa fa-check"></i><b>3.2</b> Introduccion a los test de hipótesis</a><ul>
<li class="chapter" data-level="3.2.1" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#comparando-la-estadística-de-prueba-con-el-valor-crítico."><i class="fa fa-check"></i><b>3.2.1</b> Comparando la estadística de prueba con el <strong>valor crítico</strong>.</a></li>
<li class="chapter" data-level="3.2.2" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#comparando-el-p-valor-con-el-nivel-de-significancia-alpha"><i class="fa fa-check"></i><b>3.2.2</b> Comparando el <em>p</em>-valor con el nivel de significancia <span class="math inline">\(\alpha\)</span></a></li>
<li class="chapter" data-level="3.2.3" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#comparación-del-parámetro-objetivo-con-el-intervalo-de-confianza"><i class="fa fa-check"></i><b>3.2.3</b> Comparación del parámetro objetivo con el intervalo de confianza</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#test-de-hipótesis-en-r-cálculo-e-informes"><i class="fa fa-check"></i><b>3.3</b> Test de hipótesis en R: cálculo e informes</a></li>
<li class="chapter" data-level="3.4" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#un-ejemplo-sobre-brecha-salarial-entre-géneros"><i class="fa fa-check"></i><b>3.4</b> Un ejemplo sobre brecha salarial entre géneros</a></li>
<li class="chapter" data-level="3.5" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#anova"><i class="fa fa-check"></i><b>3.5</b> ANOVA</a></li>
<li class="chapter" data-level="3.6" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#algunas-consideraciones-finales"><i class="fa fa-check"></i><b>3.6</b> Algunas consideraciones finales</a><ul>
<li class="chapter" data-level="3.6.1" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#cuando-no-se-necesita-inferencia"><i class="fa fa-check"></i><b>3.6.1</b> ¿Cuando no se necesita inferencia?</a></li>
<li class="chapter" data-level="3.6.2" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#problemas-con-los-p-valores"><i class="fa fa-check"></i><b>3.6.2</b> Problemas con los p-valores</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="intro.html"><a href="intro.html#ejercicios"><i class="fa fa-check"></i><b>3.7</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="el-muestreo-estadístico.html"><a href="el-muestreo-estadístico.html"><i class="fa fa-check"></i><b>4</b> El muestreo estadístico</a><ul>
<li class="chapter" data-level="4.1" data-path="el-muestreo-estadístico.html"><a href="el-muestreo-estadístico.html#example-one"><i class="fa fa-check"></i><b>4.1</b> Example one</a></li>
<li class="chapter" data-level="4.2" data-path="el-muestreo-estadístico.html"><a href="el-muestreo-estadístico.html#example-two"><i class="fa fa-check"></i><b>4.2</b> Example two</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="regresiones.html"><a href="regresiones.html"><i class="fa fa-check"></i><b>5</b> Regresiones</a></li>
<li class="chapter" data-level="6" data-path="estadística-multivariante.html"><a href="estadística-multivariante.html"><i class="fa fa-check"></i><b>6</b> Estadística multivariante</a></li>
<li class="chapter" data-level="" data-path="referencias.html"><a href="referencias.html"><i class="fa fa-check"></i>Referencias</a></li>
<li class="divider"></li>
<li><a href="https://github.com/geourv/quanti" target="blank">Publicado con bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Técnicas cuantitativas</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="estadística-inferencial" class="section level1">
<h1><span class="header-section-number">Capítulo 3</span> Estadística inferencial</h1>
<p>La <strong>estadísticas descriptiva</strong> es la rama de las estadística que tiene como objetivo <strong>describir y resumir un conjunto de datos</strong> de la mejor manera posible, es decir, con la menor pérdida de información posible. Con la estadística descriptiva no hay incertidumbre, porque describimos solo el grupo de observaciones en las que decidimos trabajar y no se intenta generalizar las características observadas o estudiar un grupo más grande a partir de un conjunto de datos limitado.</p>
<p>Por otro lado, <strong>La estadística inferencial</strong> es la rama de la estadística que utiliza una muestra aleatoria de datos tomados de una población para hacer inferencias, es decir, <strong>sacar conclusiones sobre la <em>población</em> de interés</strong>. En otras palabras, la información de la muestra se utiliza para hacer generalizaciones sobre el <em>parámetro</em> de interés en la población.</p>
<p>Las dos herramientas más importantes utilizadas en estadística inferencial son los test de hipótesis y los intervalos de confianza.</p>
<div id="distribuciones-de-probabilidad" class="section level2">
<h2><span class="header-section-number">3.1</span> Distribuciones de probabilidad</h2>
<p>Una distribución de probabilidad es una función que describe la probabilidad de obtener los posibles valores que puede asumir una variable aleatoria. En otras palabras, los valores de la variable varían según la distribución de probabilidad subyacente.</p>
<p>Supongamos que seleccionamos una muestra aleatoria de personas y medimos la altura de los sujetos. A medida que vamos midiendo las alturas, podemos crear una distribución de alturas. Este tipo de distribución es útil cuando necesita saber qué resultados son más probables, la dispersión de los valores potenciales y la probabilidad de resultados diferentes. Por lo tanto se puede utilizar distribuciones de probabilidad para realizar inferencias.</p>
<div id="funciones-de-r-para-distribuciones-de-probabilidad" class="section level3">
<h3><span class="header-section-number">3.1.1</span> Funciones de R para distribuciones de probabilidad</h3>
<p>R tiene varias funciones para trabajar con cada distribución de probabilidad. Hay un nombre de raíz, por ejemplo, el nombre de raíz para la distribución normal es <code>norm</code>. Esta raíz tiene como prefijo una de las letras:</p>
<ul>
<li><code>p</code> para “probabilidad”, la función de distribución acumulativa.</li>
<li><code>q</code> para “cuantil”, el inverso de la función de distribución acumulativa.</li>
<li><code>d</code> para “densidad”, la función de densidad (p. f. o p. d. f.)</li>
<li><code>r</code> para “aleatorio”, una variable aleatoria que tiene la distribución especificada</li>
</ul>
<p>Para la distribución normal, estas funciones son <code>pnorm</code>, <code>qnorm</code>, <code>dnorm</code> y <code>rnorm</code>, mientras que para la distribución binomial, estas funciones son <code>pbinom</code>, <code>qbinom</code>, <code>dbinom</code> y <code>rbinom</code>.</p>
<p>Para una distribución continua (como la normal), las funciones más útiles para resolver problemas que involucran cálculos de probabilidad son las funciones <code>p</code> y <code>q</code>, porque la densidad por la función <code>d</code> solo se puede usar para calcular probabilidades a través de integrales.</p>
<p>Para una distribución discreta (como la binomial), la función <code>d</code> calcula la densidad (p. F.), Que en este caso es una probabilidad</p>
<p><span class="math inline">\(f(x) = P(X = x)\)</span></p>
<p>y por lo tanto es útil para calcular probabilidades.</p>
<p>R tiene funciones para manejar muchas distribuciones de probabilidad. La siguiente tabla proporciona los nombres de las funciones para cada distribución y un enlace a la documentación en línea que es la referencia autorizada sobre cómo se utilizan las funciones. Pero no lea la documentación en línea todavía. Primero, pruebe los ejemplos de las secciones que siguen a la tabla.</p>
<p>library(readr)
probability_distribution_functions_in_r &lt;- read_csv(“probability-distribution-functions-in-r.csv”)</p>
<table class="table" style="font-size: 12px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:table-probability-functions">Tabla 3.1: </span>Funciones para distribución de probabilidades in R.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Distribution
</th>
<th style="text-align:left;">
p
</th>
<th style="text-align:left;">
q
</th>
<th style="text-align:left;">
d
</th>
<th style="text-align:left;">
r
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;width: 0.5in; ">
Beta
</td>
<td style="text-align:left;width: 0.7in; ">
pbeta
</td>
<td style="text-align:left;width: 1in; ">
qbeta
</td>
<td style="text-align:left;width: 1.1in; ">
dbeta
</td>
<td style="text-align:left;width: 1in; ">
rbeta
</td>
</tr>
<tr>
<td style="text-align:left;width: 0.5in; ">
Binomial
</td>
<td style="text-align:left;width: 0.7in; ">
pbinom
</td>
<td style="text-align:left;width: 1in; ">
qbinom
</td>
<td style="text-align:left;width: 1.1in; ">
dbinom
</td>
<td style="text-align:left;width: 1in; ">
rbinom
</td>
</tr>
<tr>
<td style="text-align:left;width: 0.5in; ">
Cauchy
</td>
<td style="text-align:left;width: 0.7in; ">
pcauchy
</td>
<td style="text-align:left;width: 1in; ">
qcauchy
</td>
<td style="text-align:left;width: 1.1in; ">
dcauchy
</td>
<td style="text-align:left;width: 1in; ">
rcauchy
</td>
</tr>
<tr>
<td style="text-align:left;width: 0.5in; ">
Chi-Square
</td>
<td style="text-align:left;width: 0.7in; ">
pchisq
</td>
<td style="text-align:left;width: 1in; ">
qchisq
</td>
<td style="text-align:left;width: 1.1in; ">
dchisq
</td>
<td style="text-align:left;width: 1in; ">
rchisq
</td>
</tr>
<tr>
<td style="text-align:left;width: 0.5in; ">
Exponential
</td>
<td style="text-align:left;width: 0.7in; ">
pexp
</td>
<td style="text-align:left;width: 1in; ">
qexp
</td>
<td style="text-align:left;width: 1.1in; ">
dexp
</td>
<td style="text-align:left;width: 1in; ">
rexp
</td>
</tr>
<tr>
<td style="text-align:left;width: 0.5in; ">
F
</td>
<td style="text-align:left;width: 0.7in; ">
pf
</td>
<td style="text-align:left;width: 1in; ">
qf
</td>
<td style="text-align:left;width: 1.1in; ">
df
</td>
<td style="text-align:left;width: 1in; ">
rf
</td>
</tr>
<tr>
<td style="text-align:left;width: 0.5in; ">
Gamma
</td>
<td style="text-align:left;width: 0.7in; ">
pgamma
</td>
<td style="text-align:left;width: 1in; ">
qgamma
</td>
<td style="text-align:left;width: 1.1in; ">
dgamma
</td>
<td style="text-align:left;width: 1in; ">
rgamma
</td>
</tr>
<tr>
<td style="text-align:left;width: 0.5in; ">
Geometric
</td>
<td style="text-align:left;width: 0.7in; ">
pgeom
</td>
<td style="text-align:left;width: 1in; ">
qgeom
</td>
<td style="text-align:left;width: 1.1in; ">
dgeom
</td>
<td style="text-align:left;width: 1in; ">
rgeom
</td>
</tr>
<tr>
<td style="text-align:left;width: 0.5in; ">
Hypergeometric
</td>
<td style="text-align:left;width: 0.7in; ">
phyper
</td>
<td style="text-align:left;width: 1in; ">
qhyper
</td>
<td style="text-align:left;width: 1.1in; ">
dhyper
</td>
<td style="text-align:left;width: 1in; ">
rhyper
</td>
</tr>
<tr>
<td style="text-align:left;width: 0.5in; ">
Logistic
</td>
<td style="text-align:left;width: 0.7in; ">
plogis
</td>
<td style="text-align:left;width: 1in; ">
qlogis
</td>
<td style="text-align:left;width: 1.1in; ">
dlogis
</td>
<td style="text-align:left;width: 1in; ">
rlogis
</td>
</tr>
<tr>
<td style="text-align:left;width: 0.5in; ">
Log Normal
</td>
<td style="text-align:left;width: 0.7in; ">
plnorm
</td>
<td style="text-align:left;width: 1in; ">
qlnorm
</td>
<td style="text-align:left;width: 1.1in; ">
dlnorm
</td>
<td style="text-align:left;width: 1in; ">
rlnorm
</td>
</tr>
<tr>
<td style="text-align:left;width: 0.5in; ">
Negative Binomial
</td>
<td style="text-align:left;width: 0.7in; ">
pnbinom
</td>
<td style="text-align:left;width: 1in; ">
qnbinom
</td>
<td style="text-align:left;width: 1.1in; ">
dnbinom
</td>
<td style="text-align:left;width: 1in; ">
rnbinom
</td>
</tr>
<tr>
<td style="text-align:left;width: 0.5in; ">
Normal
</td>
<td style="text-align:left;width: 0.7in; ">
pnorm
</td>
<td style="text-align:left;width: 1in; ">
qnorm
</td>
<td style="text-align:left;width: 1.1in; ">
dnorm
</td>
<td style="text-align:left;width: 1in; ">
rnorm
</td>
</tr>
<tr>
<td style="text-align:left;width: 0.5in; ">
Poisson
</td>
<td style="text-align:left;width: 0.7in; ">
ppois
</td>
<td style="text-align:left;width: 1in; ">
qpois
</td>
<td style="text-align:left;width: 1.1in; ">
dpois
</td>
<td style="text-align:left;width: 1in; ">
rpois
</td>
</tr>
<tr>
<td style="text-align:left;width: 0.5in; ">
Student t
</td>
<td style="text-align:left;width: 0.7in; ">
pt
</td>
<td style="text-align:left;width: 1in; ">
qt
</td>
<td style="text-align:left;width: 1.1in; ">
dt
</td>
<td style="text-align:left;width: 1in; ">
rt
</td>
</tr>
<tr>
<td style="text-align:left;width: 0.5in; ">
Studentized Range
</td>
<td style="text-align:left;width: 0.7in; ">
ptukey
</td>
<td style="text-align:left;width: 1in; ">
qtukey
</td>
<td style="text-align:left;width: 1.1in; ">
dtukey
</td>
<td style="text-align:left;width: 1in; ">
rtukey
</td>
</tr>
<tr>
<td style="text-align:left;width: 0.5in; ">
Uniform
</td>
<td style="text-align:left;width: 0.7in; ">
punif
</td>
<td style="text-align:left;width: 1in; ">
qunif
</td>
<td style="text-align:left;width: 1.1in; ">
dunif
</td>
<td style="text-align:left;width: 1in; ">
runif
</td>
</tr>
<tr>
<td style="text-align:left;width: 0.5in; ">
Weibull
</td>
<td style="text-align:left;width: 0.7in; ">
pweibull
</td>
<td style="text-align:left;width: 1in; ">
qweibull
</td>
<td style="text-align:left;width: 1.1in; ">
dweibull
</td>
<td style="text-align:left;width: 1in; ">
rweibull
</td>
</tr>
<tr>
<td style="text-align:left;width: 0.5in; ">
Wilcoxon Rank Sum Statistic
</td>
<td style="text-align:left;width: 0.7in; ">
pwilcox
</td>
<td style="text-align:left;width: 1in; ">
qwilcox
</td>
<td style="text-align:left;width: 1.1in; ">
dwilcox
</td>
<td style="text-align:left;width: 1in; ">
rwilcox
</td>
</tr>
<tr>
<td style="text-align:left;width: 0.5in; ">
Wilcoxon Signed Rank Statistic
</td>
<td style="text-align:left;width: 0.7in; ">
psignrank
</td>
<td style="text-align:left;width: 1in; ">
qsignrank
</td>
<td style="text-align:left;width: 1.1in; ">
dsignrank
</td>
<td style="text-align:left;width: 1in; ">
rsignrank
</td>
</tr>
</tbody>
</table>
</div>
<div id="la-distribución-binomial" class="section level3">
<h3><span class="header-section-number">3.1.2</span> La distribución binomial</h3>
</div>
<div id="la-distribución-normal" class="section level3">
<h3><span class="header-section-number">3.1.3</span> La distribución normal</h3>
</div>
</div>
<div id="introduccion-a-los-test-de-hipótesis" class="section level2">
<h2><span class="header-section-number">3.2</span> Introduccion a los test de hipótesis</h2>
<p>Primero cabe preguntarse por qué intentaríamos hacer inferencias sobre un parámetro de una población basadonos en una muestra, en lugar de simplemente recopilar datos para toda la población, calcular estadísticas que nos interesan y tomar decisiones basadas en eso. La principal razón por la que utilizamos una muestra en lugar de toda la población es porque recopilar datos sobre toda la población es más compicado o en ocasiones impracticable por varios motivos (complejidad, coste, limitación de tiempo, entre muchos otros motivos).<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a></p>
<blockquote>
<p>El objetivo general de una prueba de hipótesis es sacar conclusiones para confirmar o refutar una creencia sobre una población basándonos en un grupo más pequeño de observaciones.</p>
</blockquote>
<p>Las pruebas de hipótesis tienen muchas aplicaciones prácticas. Aquí ponemos algunos ejemplos:</p>
<ol style="list-style-type: decimal">
<li>Una media: supongamos que a un político le gustaría le gustaría probar si el salario medio de los trabajadores españoles es diferente de 1200 euros.</li>
<li>Dos medias:
<ul>
<li>Muestras independientes: supongamos que a un profesor le gustaría probar la idoneidad de un nuevo método docente midiendo la nota media para los alumnos de un grupo de control y los del grupo en el que se ha introducido la novedad.</li>
<li>Muestras pareadas o relacionadas: supongamos que el mismo profesor quisiera probar la idoneidad de este nuevo método de enseñanza pero lo hiciera midiendo los conocimientos de los alumnos antes y después de la explicación.</li>
</ul></li>
<li>Una proporción: supongamos que a un analísta político quisiera comprobar si la proporción de ciudadanos que van a votar por un candidato específico es inferior al 25%.</li>
<li>Dos proporciones: supongamos que a un geógrafo le gustaría probar si la proporción de visitantes a una playa es diferente entre jóvenes y personas mayores.</li>
<li>Una variación: supongamos que un ingeniero quisiera probar si una batería tiene una variabilidad en el timpo de carga menor que la indicada en la descripción técnica.</li>
<li>Dos variaciones: supongamos que, en una fábrica, dos líneas de producción funcionan independientemente una de la otra. El gerente querría probar si los costes del mantenimiento semanal de estas dos cadenas de producción tienen la misma variación.</li>
</ol>
<p>Por supuesto, hay muchísimas más aplicaciones potenciales y muchas preguntas de investigación pueden responderse gracias a una prueba de hipótesis.</p>
<p>Por lo general, <strong>las pruebas de hipótesis se utilizan para responder preguntas de investigación en análisis confirmatorios</strong>. Los análisis confirmatorios se refieren a análisis estadísticos donde las hipótesis — deducidas de la teoría — se definen de antemano (preferiblemente antes de la recopilación de datos). En este enfoque, la investigadora tiene una idea específica sobre las variables en consideración y está tratando de ver si su idea, especificada como hipótesis, está respaldada por datos.</p>
<p>Podemos utilizar al menos tres métodos diferentes para realizar una prueba de hipótesis comparando:</p>
<ol style="list-style-type: decimal">
<li>la estadística de prueba con el <strong>valor crítico</strong>.</li>
<li>el <strong><em>p</em>-valor</strong> con el nivel de significancia <span class="math inline">\(\alpha\)</span>.</li>
<li>el parámetro objetivo con el <strong>intervalo de confianza</strong>.</li>
</ol>
<p>Estos enfoques puede diferir en algunos aspectos pero tienen muchos puntos en común. El uso de uno u otro método es a menudo una cuestión de elección personal o de contexto.</p>
<p>Para los tres métodos, explicaré los pasos necesarios para realizar una prueba de hipótesis desde un punto de vista general y los ilustraré con la siguiente situación:.<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a></p>
<blockquote>
<p>Supongamos que un político quisiera comprobar si el salario medio de los trabajadores españoles es diferente de 1.200 euros.</p>
</blockquote>
<p>En la mayoría de las pruebas de hipótesis, la prueba que vamos a utilizar como ejemplo a continuación requiere algunas condiciones. En esta sección asumimos que se cumplen todos los supuestos pero más adelante hablaremos de esto.</p>
<div id="comparando-la-estadística-de-prueba-con-el-valor-crítico." class="section level3">
<h3><span class="header-section-number">3.2.1</span> Comparando la estadística de prueba con el <strong>valor crítico</strong>.</h3>
<p>Este metodo consiste en reproducir los siguientes 4 pasos:</p>
<ol style="list-style-type: decimal">
<li>Establecer la <strong>hipótesis nula y alternativa</strong></li>
<li>Calcular la <strong>estadística de prueba</strong></li>
<li>Encontrar el <strong>valor crítico</strong></li>
<li><strong>Concluir</strong> e interpretar los resultados</li>
</ol>
<div id="estableciendo-la-hipótesis-nula-y-alternativa" class="section level4">
<h4><span class="header-section-number">3.2.1.1</span> Estableciendo la hipótesis nula y alternativa</h4>
<p>Una prueba de hipótesis primero requiere una suposición sobre un fenómeno o hipótesis, que se deriva de la teoría y la pregunta de investigación.</p>
<p>Dado que una prueba de hipótesis se utiliza para confirmar o refutar una creencia previa, necesitamos <strong>formular nuestra creencia de modo que haya una hipótesis nula y una alternativa</strong>. Esas hipótesis deben ser <strong>mútuamente excluyentes</strong>, lo que significa que no pueden ser verdaderas al mismo tiempo. En el contexto, las hipótesis nula y alternativa son así:</p>
<ul>
<li>Hipótesis nula <span class="math inline">\(H_0:\mu=1200\)</span></li>
<li>Hipótesis alternativa <span class="math inline">\(H_1:\mu\ne 1200\)</span></li>
</ul>
<p>Al plantear la hipótesis nula y alternativa, tenga en cuenta los siguientes tres puntos:</p>
<ol style="list-style-type: decimal">
<li><em>Siempre estamos interesados en la población y no en la muestra.</em> Esta es la razón por la que <span class="math inline">\(H_0\)</span> y <span class="math inline">\(H_1\)</span> siempre se escribirán en términos de población y no en términos de muestra (en este caso, <span class="math inline">\(\mu\)</span> y no <span class="math inline">\(\overline{x}\)</span>).</li>
<li><em>La suposición que nos gustaría probar es a menudo la hipótesis alternativa.</em> Si quisieramos probar si el salario medio de los trabajadores españoles es inferior a 1200 euros, habríamos establecido que <span class="math inline">\(H_0:\mu = 1200\)</span> (o equivalentemente, <span class="math inline">\(H_0:\mu\ge 1200\)</span>) y <span class="math inline">\(H_1:\mu&lt;1200\)</span>. <strong><em>No hay que confundir la hipótesis nula con la alternativa, o las conclusiones serán diametralmente opuestas</em></strong>.</li>
<li><em>La hipótesis nula es a menudo el status quo.</em> Por ejemplo, suponiendo que un empresario quiere probar si el nuevo logo de su marca es mejor valorado que el logo anterior. El <em>status quo</em> es que los dos logos sean igualmente valorados. Suponiendo que un valor mayor es mejor, entonces se escribirá <span class="math inline">\(H_0:\mu_{nuevo}=\mu_{viejo}\)</span> (o equivalentemente, <span class="math inline">\(H_0:\mu_{nuevo} - \mu_{viejo} = 0\)</span>) y <span class="math inline">\(H_1:\mu_{nuevo}&gt;\mu_{viejo}\)</span> (o equivalentemente, <span class="math inline">\(H_0:\mu_{nuevo} - \mu_{viejo}&gt; 0\)</span>). Por el contrario, si cuanto más bajo mejor, habríamos escrito <span class="math inline">\(H_0: \mu_{nuevo} = \mu_{viejo}\)</span> (o equivalentemente, <span class="math inline">\(H_0: \mu_{nuevo} - \mu_{viejo} = 0\)</span>) y <span class="math inline">\(H_1:\mu_{nuevo} &lt;\mu_{viejo}\)</span> (o equivalentemente, <span class="math inline">\(H_0: \mu_{nuevo} - \mu_{viejo}&lt;0\)</span>).</li>
</ol>
</div>
<div id="calcular-la-estadística-de-prueba" class="section level4">
<h4><span class="header-section-number">3.2.1.2</span> Calcular la estadística de prueba</h4>
<p>La <strong>estadística de prueba</strong> (o <strong>t-stat</strong>) es una métrica que indica <strong>qué tan extremas son las observaciones en comparación con la hipótesis nula</strong>. Cuanto mayor sea el <em>t</em>-stat (en valor absoluto), más extremas serán las observaciones.</p>
<p>Hay varias fórmulas para calcular el t-stat, con una fórmula para cada tipo de prueba de hipótesis: una o dos medias, una o dos proporciones, una o dos varianzas. Esto significa que hay una fórmula para calcular el t-stat para una prueba de hipótesis en una media, otra fórmula para una prueba en dos medias, otra para una prueba en una proporción, etc.<a href="#fn4" class="footnote-ref" id="fnref4"><sup>4</sup></a> La única dificultad en este segundo paso es elegir la fórmula adecuada. Tan pronto como se sepa qué fórmula utilizar según el tipo de prueba, simplemente debe aplicársele a los datos. Afortunadamente, las fórmulas para las pruebas de hipótesis en una y dos medias, y una y dos proporciones siguen la misma estructura.</p>
<p>Calcular la estadística de prueba para estas pruebas es similar a <em>escalar</em> una variable aleatoria (un proceso también conocido como “estandarización” o “normalización”) que consiste en restar la media de esa variable aleatoria y dividir el resultado por la desviación estándar:</p>
<p><span class="math display">\[Z = \frac{X - \mu}{\sigma}\]</span>
Para estas 4 pruebas de hipótesis (una/dos medias y una/dos proporciones), calcular el estadístico de prueba es como escalar el estimador (calculado a partir de la muestra) correspondiente al parámetro de interés (en la población). Así que básicamente restamos el parámetro objetivo del estimador puntual y luego dividimos el resultado por el error estándar (que es equivalente a la desviación estándar, pero para un estimador).</p>
<p>Si esto no está claro, así es como se calcula la estadística de prueba (<span class="math inline">\(t_{obs}\)</span>) en nuestro ejemplo (asumiendo que se desconoce la varianza de la población):</p>
<p><span class="math display">\[t_{obs} = \frac{\bar{x} - \mu}{\frac{s}{\sqrt{n}}}\]</span></p>
<p>dónde:</p>
<ul>
<li><span class="math inline">\(\overline{x}\)</span> es la media de la muestra (es decir, el estimador)</li>
<li><span class="math inline">\(\mu\)</span> es la media bajo la hipótesis nula (es decir, el parámetro objetivo)</li>
<li><span class="math inline">\(s\)</span> es la desviación estándar de la muestra</li>
<li><span class="math inline">\(n\)</span> es el tamaño de la muestra</li>
<li>(<span class="math inline">\(\frac{s}{\sqrt{n}}\)</span> es el error estándar)</li>
</ul>
<p>Suponiendo que en nuestro caso tenemos una media muestral de 1150 euros (<span class="math inline">\(\overline{x} = 1150\)</span>), una desviación estándar muestral de 200 euros (<span class="math inline">\(s=200\)</span>) y un tamaño de muestra de 30 trabajadores (<span class="math inline">\(n=30\)</span>) y, teniendo en cuenta que la media poblacional (la media bajo la hipótesis nula) es 1200 euros (<span class="math inline">\(\mu=1200\)</span>), el t-stat quedaría así:</p>
<p><span class="math display">\[t_{obs} = \frac{\bar{x} - \mu}{\frac{s}{\sqrt{n}}} = \frac{1150 - 1200}{\frac{200}{\sqrt{30}}} = -1.369306\]</span></p>
<p>Aunque las fórmulas son diferentes según el parámetro que esté probando, el valor encontrado para la estadística de prueba nos da una indicación de cuán extremas son nuestras observaciones.</p>
<p>Recordemos este valor de <code>-1.369306</code> porque se volverá a utilizar al final de este test para compararlo con el valor crítico.</p>
</div>
<div id="encontrando-el-valor-crítico" class="section level4">
<h4><span class="header-section-number">3.2.1.3</span> Encontrando el valor crítico</h4>
<p>Aunque el <code>t-stat</code> nos da una indicación como de extremas son nuestras observaciones, necesitamos comparar este valor con un umbral o <strong>valor crítico</strong>, que viene dado por una <strong><em>distribución de probabilidad</em></strong>.</p>
<p>De la misma manera que la fórmula para calcular el <code>t-stat</code> es diferente para cada parámetro de interés, la distribución de probabilidad subyacente en la que se basa el <em>valor crítico</em> también es diferente para cada parámetro objetivo. Esto significa que, además de elegir la fórmula apropiada para calcular el <code>t-stat</code>, también necesitamos seleccionar la distribución de probabilidad apropiada dependiendo del parámetro que estemos probando.</p>
<p>Afortunadamente, solo hay 4 distribuciones de probabilidad diferentes para las pruebas de hipótesis cubiertas aquí (recordemos que son una/dos medias, una/dos proporciones y una/dos varianzas):</p>
<ol style="list-style-type: decimal">
<li>Distribución normal estándar:
<ul>
<li>prueba en una y dos medias con varianzas de población conocidas.</li>
<li>prueba en dos muestras donde se conoce la varianza de la diferencia entre las 2 muestras <span class="math inline">\(\sigma^2_D\)</span></li>
<li>prueba en una y dos proporciones (dado que se cumplen algunos supuestos).</li>
</ul></li>
<li>Distribución de Student:
<ul>
<li>prueba en una y dos medias con *varianza(s) de población desconocida(s).</li>
<li>prueba en dos muestras donde la varianza de la diferencia entre las 2 muestras <span class="math inline">\(\sigma^2_D\)</span> es <em>desconocida</em>.</li>
</ul></li>
<li>Distribución Chi-cuadrado:
<ul>
<li>prueba en una varianza.</li>
</ul></li>
<li>Distribution de fisher:
<ul>
<li>prueba en dos varianzas.</li>
</ul></li>
</ol>
<p>Cada distribución de probabilidad tiene sus propios parámetros, definiendo su forma y/o ubicación. Los parámetros de una distribución de probabilidad pueden verse como si fuesen marcadores de ADN; lo que significa que la distribución está completamente definida por su(s) parámetro(s).</p>
<p>Volviendo a nuestra investigación, la distribución de probabilidad subyacente de una prueba en una media es la distribución Normal estándar o de Student, dependiendo de si la varianza de la <em>población</em> (no la varianza de la muestra) es conocida o no:</p>
<ul>
<li>Si se conoce la varianza de la población <span class="math inline">\(\rightarrow\)</span>, se usa la distribución Normal estándar</li>
<li>Si la varianza de la población es <em>desconocida</em> <span class="math inline">\(\rightarrow\)</span>, se utiliza la distribución de Student</li>
</ul>
<p>Si no se proporciona explícitamente la varianza de la población, se puede suponer que es desconocida, ya que no se puede calcular basándonos en una muestra. Si pudiera calcularlo, eso significaría que tiene acceso a toda la población y, en este caso, no tiene sentido realizar una prueba de hipótesis (simplemente podría usar algunas estadísticas descriptivas para confirmar o refutar su creencia dicha hipótesis. En nuestro ejemplo, no se especifica la varianza de la población, por lo que se supone que es desconocida. Por lo tanto, usaremos la distribución de Student.</p>
<p>La distribución Student tiene un parámetro que la define: el número de grados de libertad. El número de grados de libertad depende del tipo de prueba de hipótesis. Por ejemplo, el número de grados de libertad para una prueba en una media es igual al número de observaciones menos uno (<span class="math inline">\(n-1\)</span>). Sin ir demasiado lejos en los detalles, el <span class="math inline">\(- 1\)</span> proviene del hecho de que hay una cantidad que se estima (es decir, la media). Siendo el tamaño de la muestra igual a 30 en nuestro ejemplo, los grados de libertad son iguales a <span class="math inline">\(n -1 = 30-1=29\)</span>.</p>
<p>Por último, para encontrar el valor crítico también es necesario conocer el <strong>nivel de significancia</strong> <span class="math inline">\(\alpha\)</span>, que es la <strong>probabilidad de rechazar erróneamente la hipótesis nula aunque en realidad sea verdadera</strong>. En este sentido, es un error de tipo I (en contraposición al error de tipo II) que aceptamos para poder sacar conclusiones sobre una población a partir de un subconjunto de ella.</p>
<p>En muchas aplicaciones el nivel de significancia se suele establecer en el 5%. En cambio, en algunos campos (como la medicina o la ingeniería, entre otros), el nivel de significancia también se establece a veces en el 1% para disminuir la tasa de error. Es mejor especificar el nivel de significancia <em>antes</em> de realizar una prueba de hipótesis para evitar la tentación de establecer el nivel de significancia de acuerdo con los resultados (la tentación es aún mayor cuando los resultados están al borde de ser significativos). En nuestro caso, tomamos <span class="math inline">\(\alpha = 5\% = 0.05\)</span>.</p>
<p>Además, queremos probar si el salario medio de los trabajadores españoles es <strong>diferente</strong> de 1200 euros. Si quisiéramos probar que el salario medio fuera inferior a 1200 euros (<span class="math inline">\(H_1: \mu &lt;1200\)</span>) o superior a 1200 ($ H_1: &gt;1200$), habríamos realizado una prueba unilateral. Asegúrese de realizar la prueba correcta (bilateral o unilateral) porque tiene un impacto en cómo encontrar el valor crítico.</p>
<p>Ahora que conocemos la distribución apropiada (distribución de Student), su parámetro (grados de libertad (gl) = 29), el nivel de significancia (<span class="math inline">\(\alpha\)</span> = 0.05) y la dirección (bilateral), tenemos todo lo que necesitamos para calcular el valor crítico. Podríamos localizar este valor en la tabla estadística correspondiente o directamente lo podríamos calcular con R.</p>
<p>Al observar la fila df = 29 y la columna <span class="math inline">\(t_.025\)</span> en la tabla de distribución de Student, encontramos un valor crítico de:</p>
<p><span class="math display">\[t_{n-1;\alpha/2} = t_{29; 0.025} = 2.04523\]</span></p>
<p>Tomamos <span class="math inline">\(t_{\alpha/2} = t_.025\)</span> y no <span class="math inline">\(t_\alpha = t_.05\)</span> ya que el nivel de significancia es 0.05 y estamos haciendo una prueba bilateral (de dos lados; $ H_1: 1200$), por lo que la tasa de error de 0.05 debe dividirse en 2 para encontrar el valor crítico a la derecha de la distribución. Dado que la distribución de Student es simétrica, el valor crítico a la izquierda de la distribución es simplemente: -2.04523.</p>
<p>Visualmente, la tasa de error de 0.05 se divide en dos partes:</p>
<ul>
<li>0,025 a la izquierda de -2,04523 y</li>
<li>0,025 a la derecha de 2,04523</li>
</ul>
<p><img src="tecnicas-cuantitativas_files/figure-html/unnamed-chunk-48-1.png" width="672" /></p>
<p>Al igual que en el apartado anterior, cabe recordar estos valores críticos de -2,045 y 2,045 el último paso.</p>
<p>Las áreas sombreadas en rojo en el gráfico anterior también se conocen como regiones de rechazo.</p>
<p>Estos valores críticos también se pueden encontrar en R, gracias a la función <code>qt ()</code>:</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="estadística-inferencial.html#cb112-1"></a><span class="kw">qt</span>(<span class="fl">0.025</span>, <span class="dt">df =</span> <span class="dv">29</span>, <span class="dt">lower.tail =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] -2.04523</code></pre>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="estadística-inferencial.html#cb114-1"></a><span class="kw">qt</span>(<span class="fl">0.025</span>, <span class="dt">df =</span> <span class="dv">29</span>, <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 2.04523</code></pre>
<p>Como se ha visto en el tema sobre distribuciones de probabilidad, la función <code>qt ()</code> se usa para la distribución de Student (<code>q</code> significa cuantil y<code>t</code> para Student). Cabe recordar que hay otras funciones que acompañan a las diferentes distribuciones:</p>
<ul>
<li><code>qnorm ()</code> para la distribución Normal</li>
<li><code>qchisq ()</code> para la distribución Chi-cuadrado</li>
<li><code>qf ()</code> para la distribución de Fisher</li>
</ul>
</div>
<div id="conclusión-e-interpretación-de-los-resultados" class="section level4">
<h4><span class="header-section-number">3.2.1.4</span> Conclusión e interpretación de los resultados</h4>
<p>Las únicas dos posibilidades al concluir una prueba de hipótesis son:</p>
<ol style="list-style-type: decimal">
<li>Rechazo de la hipótesis nula, o</li>
<li>No rechazo de la hipótesis nula</li>
</ol>
<p>En nuestro ejemplo sobre los salarios de los españoles, recordamos que hemos determinado que el:</p>
<ul>
<li>el <code>t-stat</code> es -1.369306, y</li>
<li>los valores críticos son -2.04523 y 2.04523</li>
</ul>
<p>Recordemos que:</p>
<ul>
<li>el <strong>t-stat da una indicación de cuán extrema es nuestra muestra</strong> en comparación con la hipótesis nula</li>
<li>los <strong>valores críticos son el umbral a partir del cual el t-stat se considera <em>demasiado</em> extremo</strong></li>
</ul>
<p>Para comparar el <code>t-stat</code> con los valores críticos de manera gráfica:</p>
<p><img src="tecnicas-cuantitativas_files/figure-html/unnamed-chunk-50-1.png" width="672" /></p>
<p>Los dos valores críticos forman las regiones de rechazo (las áreas sombreadas en rojo):</p>
<ul>
<li>de <span class="math inline">\(-\infty\)</span> a -2.045, y</li>
<li>de 2.045 a <span class="math inline">\(\infty\)</span></li>
</ul>
<p>Si el <strong><em>t-stat</em> se encuentra dentro de una de estas regiones, rechazamos la hipótesis nula</strong>. Por el contrario, si <strong>t-stat <em>no</em> se encuentra dentro de ninguna de las regiones, no rechazamos la hipótesis nula</strong>.</p>
<p>Como podemos ver en el gráfico anterior, el <em>t-stat</em> es menos extremo que el valor crítico. En conclusión, no rechazamos la hipótesis nula de que <span class="math inline">\(\mu = 1200\)</span>.</p>
<p>Esta es la conclusión en términos estadísticos, pero no tienen sentido sin una interpretación adecuada. Por tanto, es una buena práctica interpretar también el resultado en el contexto del problema:</p>
<blockquote>
<p>Con un nivel de significancia del 5%, no rechazamos la hipótesis de que el salario medio de los trabajadores españoles es de 1200 euros.</p>
</blockquote>
<p>¿Qué significa esto realmente? Dicho de otro modo:</p>
<blockquote>
<p>“nosotros <em>no rechazamos</em> la hipótesis nula” y “nosotros <em>no rechazamos</em> la hipótesis de que el salario medio de los trabajadores españoles es igual a 1200 euros”. No escribimos “<em>aceptamos o estamos de acuerdo con</em> la hipótesis nula” ni “el salario medio de los trabajadores españoles es de 1200 euros”.</p>
</blockquote>
<p>En los test de hipótesis, llegamos a una conclusión sobre la población a partir de una muestra. Por tanto, siempre existe cierta incertidumbre y no podemos decir que estemos seguros al 100% de que nuestra conclusión sea correcta.</p>
<p>Quizás sea el caso de que el salario medio de los trabajadores españoles sea en realidad diferente a 1200 euros, pero <strong>no lo pudimos demostrar</strong> con los datos disponibles. Si tuviéramos más observaciones hubiéramos rechazado la hipótesis nula (dado que todo lo demás es igual, un tamaño de muestra más grande implica un <code>t-stat</code> más extremo). O puede darse el caso de que, incluso con más observaciones, no hubiéramos rechazado la hipótesis nula porque el salario de los trabajadores españoles en realidad se acerca a los 1200 euros. Con los datos disponibles no podemos distinguir entre estas dos posibilidades. Simplemente debemos admitir que no encontramos suficiente evidencia en contra de la hipótesis de partida, pero tampoco concluimos que la media sea igual a 1200 euros.</p>
</div>
</div>
<div id="comparando-el-p-valor-con-el-nivel-de-significancia-alpha" class="section level3">
<h3><span class="header-section-number">3.2.2</span> Comparando el <em>p</em>-valor con el nivel de significancia <span class="math inline">\(\alpha\)</span></h3>
<p>Este método consiste en los siguientes pasos:</p>
<ol style="list-style-type: decimal">
<li>Enunciar las <strong>hipótesis nula y alternativa</strong></li>
<li>Calcular la <strong>estadística de prueba</strong> (<code>t-stat</code>).</li>
<li>Calcular el <strong><em>p</em>-valor</strong></li>
<li><strong>Concluir</strong> e interpretar los resultados</li>
</ol>
<p>En este segundo método que utiliza el valor <em>p</em>, los dos primeros pasos son similares a los del primer método, mientras que la interpretación de los resultados tiene algunos puntos en común.</p>
<div id="establecer-las-hipótesis" class="section level4">
<h4><span class="header-section-number">3.2.2.1</span> Establecer las hipótesis</h4>
<p>Las hipótesis de investigación (nula y alternativa) siguen siendo las mismas:</p>
<ul>
<li><span class="math inline">\(H_0:\mu= 1200\)</span></li>
<li><span class="math inline">\(H_1:\mu\ne 1200\)</span></li>
</ul>
</div>
<div id="calcular-la-estadística-de-prueba-1" class="section level4">
<h4><span class="header-section-number">3.2.2.2</span> Calcular la estadística de prueba</h4>
<p>Cabe recordar que la fórmula del estadístico t es diferente según el tipo de prueba de hipótesis (una o dos medias, una o dos proporciones, una o dos varianzas). En nuestro caso de una sola media con varianza desconocida, tenemos que:</p>
<p><span class="math display">\[t_{obs} = \frac{\bar{x} - \mu}{\frac{s}{\sqrt{n}}} = \frac{1150 - 1200}{\frac{200}{\sqrt{30}}} = -1.369306\]</span></p>
</div>
<div id="calculo-del-valor-p" class="section level4">
<h4><span class="header-section-number">3.2.2.3</span> Calculo del valor <em>p</em></h4>
<p>El <strong><em>p</em>-valor</strong> es la probabilidad (de 0 a 1) de observar una muestra al menos tan extrema como la que observamos si la hipótesis nula fuera cierta. Dicho de otro modo: <strong>¿cómo de probable es la hipótesis nula?</strong>. También se define como el nivel de significancia más pequeño para el cual los datos indican el rechazo de la hipótesis nula.</p>
<p>Formalmente, el valor <em>p</em> es el área más allá del estadístico de prueba. Como estamos haciendo una prueba bidireccional, el valor <em>p</em> es, por lo tanto, la suma del área por encima de 1,369306 y por debajo de -1,369306.</p>
<p>Visualmente, el valor <em>p</em> es la suma de las dos áreas sombreadas en azul en la siguiente gráfica:</p>
<p><img src="tecnicas-cuantitativas_files/figure-html/unnamed-chunk-51-1.png" width="672" /></p>
<p>El valor <em>p</em> se puede obtener también con tablas estadísticas o es posible calcularlo con precisión en R con la función <code>pt()</code>:</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="estadística-inferencial.html#cb116-1"></a>p_val &lt;-<span class="st"> </span><span class="kw">pt</span>(<span class="op">-</span><span class="fl">1.369306</span>, <span class="dt">df =</span> <span class="dv">29</span>, <span class="dt">lower.tail =</span> <span class="ot">TRUE</span>) <span class="op">+</span><span class="st"> </span><span class="kw">pt</span>(<span class="fl">1.369306</span>, <span class="dt">df =</span> <span class="dv">29</span>, <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)</span>
<span id="cb116-2"><a href="estadística-inferencial.html#cb116-2"></a>p_val</span></code></pre></div>
<pre><code>## [1] 0.1814156</code></pre>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="estadística-inferencial.html#cb118-1"></a><span class="co"># Que es lo mismo que...</span></span>
<span id="cb118-2"><a href="estadística-inferencial.html#cb118-2"></a>p_val &lt;-<span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="kw">pt</span>(<span class="fl">1.369306</span>, <span class="dt">df =</span> <span class="dv">29</span>, <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)</span>
<span id="cb118-3"><a href="estadística-inferencial.html#cb118-3"></a>p_val</span></code></pre></div>
<pre><code>## [1] 0.1814156</code></pre>
<p>El valor <em>p</em> es 0.1814, que indica que hay un 18.14% de probabilidad de observar una muestra al menos tan extrema como la observada si el hipótesis nula eran verdaderas. Esto ya nos da una pista sobre si nuestro t-stat es demasiado extremo o no (y, por lo tanto, si nuestra hipótesis nula es probable o no).</p>
<p>Como la función <code>qt()</code> para encontrar el valor crítico, usamos <code>pt()</code> para encontrar el valor <em>p</em> porque la distribución subyacente es la distribución de Student. En otros casos se utilizarían las funciones <code>pnorm ()</code>, <code>pchisq ()</code> y <code>pf ()</code> para las otras distribuciones mencionadas anteriormente (Normal, Chi-cuadrado y Fisher).</p>
</div>
<div id="concluir-e-interpretar-los-resultados" class="section level4">
<h4><span class="header-section-number">3.2.2.4</span> Concluir e interpretar los resultados</h4>
<p>Finalmente, hay que comparar el valor <em>p</em> que acabamos de calcular con el nivel de significancia <span class="math inline">\(\alpha\)</span>. Como para todas las pruebas estadísticas:</p>
<ul>
<li>Si el <strong><em>p</em>-valor es menor</strong> que <span class="math inline">\(\alpha\)</span> (p-valor<span class="math inline">\(&lt;0.05\)</span>), entonces <span class="math inline">\(H_0\)</span> es poco probable <span class="math inline">\(\rightarrow\)</span> <strong>rechazamos</strong> la hipótesis nula.</li>
<li>Si el <strong><em>p</em>-valor es mayor que o igual</strong> a <span class="math inline">\(\alpha\)</span> (<em>p</em>-valor <span class="math inline">\(\ge 0.05\)</span>), entonces <span class="math inline">\(H_0\)</span> es probable <span class="math inline">\(\rightarrow\)</span> <strong>no podemos rechazar</strong> la hipótesis nula.</li>
</ul>
<p>No importa si tomamos en consideración el <em>p</em>-valor exacto (es decir, 0.1814) o el acotado (0.05 &lt;<em>p</em>-valor &lt;0.10), es mayor que 0.05, entonces no rechazamos la hipótesis nula. En el contexto del problema, no rechazamos la hipótesis nula de que el salario medio de los trabajadores españoles es igual a 1200 euros.</p>
<p>El resultado obtenido ha sido el mismo que en el primer método. Evidentemente, debería dar lo mismo si se usan los mismos datos y con el mismo nivel de significancia.</p>
</div>
</div>
<div id="comparación-del-parámetro-objetivo-con-el-intervalo-de-confianza" class="section level3">
<h3><span class="header-section-number">3.2.3</span> Comparación del parámetro objetivo con el intervalo de confianza</h3>
<p>Este método consiste en calcular primero el intervalo de confianza y comparar sobre éste el parámetro objetivo (el parámetro bajo la hipótesis nula). Podemos distinguir tres pasos:</p>
<ol style="list-style-type: decimal">
<li>Enunciar las <strong>hipótesis nula y alternativa</strong></li>
<li>Calcular el <strong>intervalo de confianza</strong></li>
<li><strong>Concluir</strong> e interpretar los resultados</li>
</ol>
<p>También se pueden apreciar varias similitudes con los métodos anteriores.</p>
<div id="enunciar-las-hipótesis" class="section level4">
<h4><span class="header-section-number">3.2.3.1</span> Enunciar las hipótesis</h4>
<p>Nuevamente, las hipótesis nula y alternativa siguen siendo las mismas:</p>
<ul>
<li><span class="math inline">\(H_0:\mu = 1200\)</span></li>
<li><span class="math inline">\(H_1:\mu\ne 1200\)</span></li>
</ul>
</div>
<div id="calcular-el-intervalo-de-confianza" class="section level4">
<h4><span class="header-section-number">3.2.3.2</span> Calcular el intervalo de confianza</h4>
<p>Al igual que los test de hipótesis, los intervalos de confianza son una herramienta bien conocida en la estadística inferencial. El <strong>intervalo de confianza</strong> es un procedimiento de estimación que produce un <strong>intervalo que contiene el parámetro verdadero con una cierta probabilidad</strong>.</p>
<p>De la misma manera que existe una fórmula para cada tipo de prueba de hipótesis al calcular las estadísticas de la prueba, existe una fórmula para cada tipo de intervalo de confianza. La fórmula para calcular un intervalo de confianza en una media <span class="math inline">\(\mu\)</span> (con varianza poblacional desconocida):
<span class="math display">\[
(1-\alpha)\% \text{ IC para } \mu=\overline{x}\pm t_{\alpha/2, n - 1}\frac{s}{\sqrt{n}}
\]</span>
donde <span class="math inline">\(t_{\alpha/2, n-1}\)</span> se encuentra en la tabla de distribución de Student o se puede calcular con R (y es similar al valor crítico encontrado en el primer método).</p>
<p>Dados nuestros datos y con <span class="math inline">\(\alpha= 0.05\)</span>, tenemos que:
<span class="math display">\[
\begin{aligned}
 95\%\text{ IC para } \mu 
    &amp;= \bar{x} \pm t_{\alpha/2, n - 1} \frac{s}{\sqrt{n}} \\
    &amp;= 1150 \pm 2.045 \frac{200}{\sqrt{30}} \\
    &amp;= [1075,33; 1224,67]
\end{aligned}
\]</span></p>
<p>El intervalo de confianza del 95% para <span class="math inline">\(\mu\)</span> es [1075,33; 1224,67] euros. <strong>¿Qué significa este intervalo de confianza del 95%? </strong></p>
<p>Sabemos que este procedimiento de estimación tiene una probabilidad del 95% de producir un intervalo que contenga la media verdadera <span class="math inline">\(\mu\)</span>. En otras palabras, <strong>si construimos muchos intervalos de confianza</strong> (con diferentes muestras del mismo tamaño), <strong>el 95% de ellos incluirá la media de la población</strong> (el verdadero parámetro). Del mismo modo el 5% de estos intervalos de confianza no cubrirán la media real.</p>
<p>Si desea disminuir este último porcentaje, puede disminuir el nivel de significancia (por ejemplo <span class="math inline">\(\alpha= 0.01\)</span>). En igualdad de condiciones, esto disminuirá el rango del intervalo de confianza y, por lo tanto, aumentará la probabilidad de que incluya el parámetro verdadero.</p>
</div>
<div id="conclusión-e-interpretación-de-los-resultados-1" class="section level4">
<h4><span class="header-section-number">3.2.3.3</span> Conclusión e interpretación de los resultados</h4>
<p>Finalmente, hay comparar el intervalo de confianza con el valor del parámetro objetivo (el valor cuestionado por la hipótesis nula):</p>
<ul>
<li>Si el <strong>intervalo de confianza no incluye</strong> el valor hipotético, <span class="math inline">\(H_0\)</span> es poco probable <span class="math inline">\(\rightarrow\)</span> <strong>rechazamos</strong> la hipótesis nula.</li>
<li>Si el <strong>intervalo de confianza incluye</strong> el valor hipotético, <span class="math inline">\(H_0\)</span> es probable <span class="math inline">\(\rightarrow\)</span>, <strong>no rechazamos</strong> la hipótesis nula</li>
</ul>
<p>En nuestro ejemplo:</p>
<ul>
<li>el valor hipotético es 1200 (desde $ H_0:= 1200$)</li>
<li>1200 se incluye en el intervalo de confianza del 95%, ya que va de 1075,33 a 1224,67 euros</li>
<li>Entonces <strong>no rechazamos</strong> la hipótesis nula de que el salario medio de los trabajadores españoles sea de 1200 euros.</li>
</ul>
<p>Por supuesto, la conclusión es equivalente a la que se había llegado por los otros dos métodos. Esto debe ser así, ya que usamos los mismos datos y el mismo nivel de significancia <span class="math inline">\(\alpha\)</span> para los tres métodos.</p>
</div>
</div>
</div>
<div id="test-de-hipótesis-en-r-cálculo-e-informes" class="section level2">
<h2><span class="header-section-number">3.3</span> Test de hipótesis en R: cálculo e informes</h2>
<p><El ejemplo anterior pero en el mínimo número de pasos></p>
</div>
<div id="un-ejemplo-sobre-brecha-salarial-entre-géneros" class="section level2">
<h2><span class="header-section-number">3.4</span> Un ejemplo sobre brecha salarial entre géneros</h2>
</div>
<div id="anova" class="section level2">
<h2><span class="header-section-number">3.5</span> ANOVA</h2>
</div>
<div id="algunas-consideraciones-finales" class="section level2">
<h2><span class="header-section-number">3.6</span> Algunas consideraciones finales</h2>
<div id="cuando-no-se-necesita-inferencia" class="section level3">
<h3><span class="header-section-number">3.6.1</span> ¿Cuando no se necesita inferencia?</h3>
<p>Hemos analizado varios ejemplos sobre cómo realizar inferencias estadísticas: realización de test de hipótesis y construcción de intervalos de confianza. Antes de empezar a realizar un experimento, siempre es necesario realizar un análisis exploratorio de los datos. Este primer vistazo siempre puede ayudar a intuir sobre lo que los métodos estadísticos como los intervalos de confianza y las pruebas de hipótesis pueden decirnos (y lo que no pueden). En los apartados anteriores hemos querido explicar cómo funciona la inferencia pero no nos hemos preguntado si era realmente necesaria.</p>
<p>Consideremos un ejemplo. Supongamos que estamos interesados en la siguiente pregunta: De <em>todos</em> los vuelos que salen de un aeropuerto de la ciudad de Nueva York, ¿los vuelos de Hawaiian Airlines están en el aire por más tiempo que los vuelos de Alaska Airlines? Además, supongamos que los vuelos de 2013 son una muestra representativa de todos esos vuelos. Entonces podemos usar el dataframe <code>flights</code> disponible en el paquete <code>nycflights13</code> para responder nuestra pregunta. Filtremos este dataframe para incluir solo a Hawaiian y Alaska Airlines usando sus códigos de “operador” “HA” y “AS”:</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="estadística-inferencial.html#cb120-1"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb120-2"><a href="estadística-inferencial.html#cb120-2"></a><span class="kw">library</span>(nycflights13)</span>
<span id="cb120-3"><a href="estadística-inferencial.html#cb120-3"></a>flights_sample &lt;-<span class="st"> </span>flights <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb120-4"><a href="estadística-inferencial.html#cb120-4"></a><span class="st">  </span><span class="kw">filter</span>(carrier <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;HA&quot;</span>, <span class="st">&quot;AS&quot;</span>))</span></code></pre></div>
<p>Hay dos posibles métodos de inferencia estadística que podríamos utilizar para responder a estas preguntas. Primero, podríamos construir un intervalo de confianza del 95% para la diferencia en las medias poblacionales <span class="math inline">\(\mu_{HA}-\mu_{AS}\)</span>, donde <span class="math inline">\(\mu_{HA}\)</span> es el tiempo de vuelo medio de todos los vuelos de Hawaiian Airlines y <span class="math inline">\(\mu_{AS}\)</span> es el tiempo medio de vuelo de los vuelos de Alaska Airlines. Luego podríamos verificar si la totalidad del intervalo es mayor que 0, sugiriendo que <span class="math inline">\(\mu_{HA} - \mu_{AS}&gt; 0\)</span>, o, en otras palabras, sugiriendo que <span class="math inline">\(\mu_{HA}&gt; \mu_{AS}\)</span>. En segundo lugar, podríamos realizar una prueba de hipótesis de la hipótesis nula <span class="math inline">\(H_0:\mu_{HA} - \mu_{AS} = 0\)</span> frente a la hipótesis alternativa <span class="math inline">\(H_A:\mu_{HA}-\mu_{AS}&gt;0\)</span>.</p>
<p>Construyamos primero una visualización exploratoria como acabamos de sugerir. Dado que <code>air_time</code> es numérico y <code>carrier</code> es categórico, un diagrama de caja (<em>boxplot</em>) puede mostrar la relación entre estas dos variables (ver la Figura <a href="estadística-inferencial.html#fig:ha-as-flights-boxplot">3.1</a>).</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="estadística-inferencial.html#cb121-1"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> flights_sample, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> carrier, <span class="dt">y =</span> air_time)) <span class="op">+</span></span>
<span id="cb121-2"><a href="estadística-inferencial.html#cb121-2"></a><span class="st">  </span><span class="kw">geom_boxplot</span>() <span class="op">+</span></span>
<span id="cb121-3"><a href="estadística-inferencial.html#cb121-3"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Carrier&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Air Time&quot;</span>)</span></code></pre></div>
<div class="figure"><span id="fig:ha-as-flights-boxplot"></span>
<img src="tecnicas-cuantitativas_files/figure-html/ha-as-flights-boxplot-1.png" alt="Air time for Hawaiian and Alaska Airlines flights departing NYC in 2013." width="672" />
<p class="caption">
Figura 3.1: Air time for Hawaiian and Alaska Airlines flights departing NYC in 2013.
</p>
</div>
<p>Esto es lo que nos gusta llamar momentos en los que “no se necesita un doctorado en estadística”. No es necesario ser un experto en estadísticas para saber que Alaska Airlines y Hawaiian Airlines tienen horarios aéreos <em>significativamente</em> diferentes. ¡Los dos diagramas de caja ni siquiera se superponen! La construcción de un intervalo de confianza o la realización de una prueba de hipótesis, francamente, no proporcionaría mucha más información que la Figura <a href="estadística-inferencial.html#fig:ha-as-flights-boxplot">3.1</a>.</p>
<p>Investiguemos por qué observamos una diferencia tan clara entre estas dos aerolíneas que utilizan la manipulación de datos. Primero agrupemos por las filas de <code>vuelos_muestra</code> no solo por<code>transportista</code> sino también por destino <code>dest</code>. Posteriormente, calcularemos dos estadísticas resumidas: el número de observaciones usando <code>n ()</code> y el tiempo medio de transmisión:</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="estadística-inferencial.html#cb122-1"></a>flights_sample <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb122-2"><a href="estadística-inferencial.html#cb122-2"></a><span class="st">  </span><span class="kw">group_by</span>(carrier, dest) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb122-3"><a href="estadística-inferencial.html#cb122-3"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">n =</span> <span class="kw">n</span>(), <span class="dt">mean_time =</span> <span class="kw">mean</span>(air_time, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 2 x 4
## # Groups:   carrier [2]
##   carrier dest      n mean_time
##   &lt;chr&gt;   &lt;chr&gt; &lt;int&gt;     &lt;dbl&gt;
## 1 AS      SEA     714      326.
## 2 HA      HNL     342      623.</code></pre>
<p>Resulta que desde la ciudad de Nueva York en 2013, Alaska solo voló a “SEA” (Seattle) desde la ciudad de Nueva York (NYC) mientras que Hawaiian solo voló a “HNL” (Honolulu) desde Nueva York. Dada la clara diferencia en la distancia entre la ciudad de Nueva York y Seattle y la ciudad de Nueva York a Honolulu, no es sorprendente que observemos tiempos de vuelo tan diferentes (_ estadísticamente significativamente diferentes_, de hecho) en los vuelos.</p>
<p>Este es un claro ejemplo de que no es necesario hacer nada más que un simple análisis exploratorio de datos utilizando visualización de datos y estadísticas descriptivas para llegar a una conclusión adecuada. Por lo tanto, es recomendable empezar siempre por realizar un análisis exploratorio con estadísticas descriptivas antes de aplicar inferencia estadística.</p>
</div>
<div id="problemas-con-los-p-valores" class="section level3">
<h3><span class="header-section-number">3.6.2</span> Problemas con los p-valores</h3>
<p>Además de los muchos malentendidos comunes sobre las pruebas de hipótesis y los valores de <span class="math inline">\(p\)</span> que hemos comentado al explicar la interpretación de las pruebas de hipótesis, otra consecuencia desafortunada del uso ampliado de los valores de <span class="math inline">\(p\)</span> y las pruebas de hipótesis es un fenómeno conocido como “p-hacking”, que es es el acto de “seleccionar” sólo los resultados que son “estadísticamente significativos” y descartar los que no lo son, aunque sea a expensas de las ideas científicas. Hay muchos artículos escritos recientemente sobre malentendidos y problemas con los valores de <span class="math inline">\(p\)</span>. Le recomendamos que consulte algunos de ellos:</p>
<ol style="list-style-type: decimal">
<li><a href="https://en.wikipedia.org/wiki/Misunderstandings_of_p-values">Malentendidos de los valores de <span class="math inline">\(p\)</span></a></li>
<li><a href="https://www.vox.com/science-and-health/2017/7/31/16021654/p-%20valores-significación-estadística-redefinir-0005">Qué debate más nerd sobre los valores de <span class="math inline">\(p\)</span> sobre la ciencia y cómo solucionarlo</a></li>
<li><a href="https://www.nature.com/news/statisticians-issue-warning-over-misuse-of-p-values-1.19503">Los estadísticos emiten una advertencia sobre el uso indebido de los valores de <span class="math inline">\(p\)</span></a></li>
<li><a href="https://fivethirtyeight.com/features/you-cant-trust-what-you-read-about-nutrition/">No puede confiar en lo que lee sobre nutrición</a></li>
<li><a href="http://www.fharrell.com/post/pval-litany/">Una letanía de problemas con valores p</a></li>
</ol>
<p>Tales problemas se estaban volviendo tan recurrentes que la Asociación Estadounidense de Estadística (ASA) emitió una declaración en 2016 titulada, <a href="https://www.amstat.org/asa/files/pdfs/P-ValueStatement.pdf">“Declaración de la ASA sobre la importancia estadística y los valores de <span class="math inline">\(p\)</span>”</a> con seis principios subyacentes al uso e interpretación adecuados de los valores de <span class="math inline">\(p\)</span>. La ASA publicó esta guía sobre los valores de <span class="math inline">\(p\)</span> para mejorar la conducta y la interpretación de la ciencia cuantitativa y para informar el creciente énfasis en la reproducibilidad de la investigación científica.</p>
<p>Quizás el uso de intervalos de confianza para la inferencia estadística permita evitar ciertos malentendidos. Sin embargo, en muchos campos todavía se usan exclusivamente valores de <span class="math inline">\(p\)</span> para la inferencia estadística y esta es una razón para incluirlos en este texto.</p>
</div>
</div>
<div id="ejercicios" class="section level2">
<h2><span class="header-section-number">3.7</span> Ejercicios</h2>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="2">
<li id="fn2"><p>Por ejemplo, una investigación podría consistir en conocer si la población de la provincia de Tarragona está satisfecha con el nuevo plan de movilidad. Si pudiéramos preguntar a toda la población en un período de tiempo razonable, no haríamos ninguna estadística inferencial. No obstante, aún habria que decidir que preguntas se les hace para entender mejor el motivo de su grado de satisfacción, complicando y encareciendo aún más la encuesta.<a href="estadística-inferencial.html#fnref2" class="footnote-back">↩︎</a></p></li>
<li id="fn3"><p>Puede ver más o menos pasos en otros artículos o libros de texto, dependiendo de si estos pasos son detallados o concisos. Sin embargo, la prueba de hipótesis debe seguir el mismo proceso independientemente del número de pasos<a href="estadística-inferencial.html#fnref3" class="footnote-back">↩︎</a></p></li>
<li id="fn4"><p>Incluso hay diferentes fórmulas dentro de cada tipo de prueba, dependiendo de si se cumplen o no algunos supuestos.<a href="estadística-inferencial.html#fnref4" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="estadística-descriptiva.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="el-muestreo-estadístico.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["tecnicas-cuantitativas.pdf", "tecnicas-cuantitativas.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
