<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 2 Estadística descriptiva | Técnicas cuantitativas</title>
  <meta name="description" content="Este documento forma parte de los materiales para la asignatura ‘Técnicas cuantitativas’ del Máster universitario en planificación, gobernanza y liderazgo territorial" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 2 Estadística descriptiva | Técnicas cuantitativas" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Este documento forma parte de los materiales para la asignatura ‘Técnicas cuantitativas’ del Máster universitario en planificación, gobernanza y liderazgo territorial" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 2 Estadística descriptiva | Técnicas cuantitativas" />
  
  <meta name="twitter:description" content="Este documento forma parte de los materiales para la asignatura ‘Técnicas cuantitativas’ del Máster universitario en planificación, gobernanza y liderazgo territorial" />
  

<meta name="author" content="Enric Aguilar y Benito Zaragozí" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="intro.html"/>
<link rel="next" href="estadística-inferencial.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script src="libs/htmlwidgets-1.5.2/htmlwidgets.js"></script>
<script src="libs/d3-3.3.8/d3.min.js"></script>
<script src="libs/dagre-0.4.0/dagre-d3.min.js"></script>
<link href="libs/mermaid-0.3.0/dist/mermaid.css" rel="stylesheet" />
<script src="libs/mermaid-0.3.0/dist/mermaid.slim.min.js"></script>
<link href="libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet" />
<script src="libs/chromatography-0.1/chromatography.js"></script>
<script src="libs/DiagrammeR-binding-1.0.6.1/DiagrammeR.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Técnicas cuantitativas</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Antes de empezar</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#prerrequisitos"><i class="fa fa-check"></i><b>0.1</b> Prerrequisitos</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#tipos-de-ficheros"><i class="fa fa-check"></i><b>0.2</b> Tipos de ficheros</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#un-ejemplo-muy-sencillo"><i class="fa fa-check"></i><b>0.3</b> Un ejemplo muy sencillo</a></li>
<li class="chapter" data-level="0.4" data-path="index.html"><a href="index.html#estructura-básica-de-un-documento-markdown"><i class="fa fa-check"></i><b>0.4</b> Estructura básica de un documento Markdown</a><ul>
<li class="chapter" data-level="0.4.1" data-path="index.html"><a href="index.html#cabecera"><i class="fa fa-check"></i><b>0.4.1</b> Cabecera</a></li>
<li class="chapter" data-level="0.4.2" data-path="index.html"><a href="index.html#insertar-código-r"><i class="fa fa-check"></i><b>0.4.2</b> Insertar código R</a></li>
<li class="chapter" data-level="0.4.3" data-path="index.html"><a href="index.html#formatos-de-texto"><i class="fa fa-check"></i><b>0.4.3</b> Formatos de texto</a></li>
<li class="chapter" data-level="0.4.4" data-path="index.html"><a href="index.html#generando-el-documento"><i class="fa fa-check"></i><b>0.4.4</b> Generando el documento</a></li>
</ul></li>
<li class="chapter" data-level="0.5" data-path="index.html"><a href="index.html#ejercicio"><i class="fa fa-check"></i><b>0.5</b> Ejercicio</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introducción</a><ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#r-como-lenguaje-de-programación"><i class="fa fa-check"></i><b>1.1</b> R como lenguaje de programación</a></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#utilizando-rstudio"><i class="fa fa-check"></i><b>1.2</b> Utilizando RStudio</a></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#interpretación-de-valores"><i class="fa fa-check"></i><b>1.3</b> Interpretación de valores</a></li>
<li class="chapter" data-level="1.4" data-path="intro.html"><a href="intro.html#variables"><i class="fa fa-check"></i><b>1.4</b> Variables</a></li>
<li class="chapter" data-level="1.5" data-path="intro.html"><a href="intro.html#tipos-basicos"><i class="fa fa-check"></i><b>1.5</b> Tipos basicos</a><ul>
<li class="chapter" data-level="1.5.1" data-path="intro.html"><a href="intro.html#números"><i class="fa fa-check"></i><b>1.5.1</b> Números</a></li>
<li class="chapter" data-level="1.5.2" data-path="intro.html"><a href="intro.html#lógicos-o-booleanos"><i class="fa fa-check"></i><b>1.5.2</b> Lógicos o booleanos</a></li>
<li class="chapter" data-level="1.5.3" data-path="intro.html"><a href="intro.html#cádenas-de-caracteres"><i class="fa fa-check"></i><b>1.5.3</b> Cádenas de caracteres</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="intro.html"><a href="intro.html#estructuras-de-datos"><i class="fa fa-check"></i><b>1.6</b> Estructuras de datos</a><ul>
<li class="chapter" data-level="1.6.1" data-path="intro.html"><a href="intro.html#vectores"><i class="fa fa-check"></i><b>1.6.1</b> Vectores</a></li>
<li class="chapter" data-level="1.6.2" data-path="intro.html"><a href="intro.html#listas"><i class="fa fa-check"></i><b>1.6.2</b> Listas</a></li>
<li class="chapter" data-level="1.6.3" data-path="intro.html"><a href="intro.html#matrices"><i class="fa fa-check"></i><b>1.6.3</b> Matrices</a></li>
<li class="chapter" data-level="1.6.4" data-path="intro.html"><a href="intro.html#data-frames"><i class="fa fa-check"></i><b>1.6.4</b> Data frames</a></li>
<li class="chapter" data-level="1.6.5" data-path="intro.html"><a href="intro.html#factores"><i class="fa fa-check"></i><b>1.6.5</b> Factores</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="intro.html"><a href="intro.html#funciones"><i class="fa fa-check"></i><b>1.7</b> Funciones</a></li>
<li class="chapter" data-level="1.8" data-path="intro.html"><a href="intro.html#tidyverse"><i class="fa fa-check"></i><b>1.8</b> Tidyverse</a><ul>
<li class="chapter" data-level="1.8.1" data-path="intro.html"><a href="intro.html#stringr"><i class="fa fa-check"></i><b>1.8.1</b> stringr</a></li>
<li class="chapter" data-level="1.8.2" data-path="intro.html"><a href="intro.html#el-operador-pipe"><i class="fa fa-check"></i><b>1.8.2</b> El operador <code>pipe</code></a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="intro.html"><a href="intro.html#ejercicios"><i class="fa fa-check"></i><b>1.9</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html"><i class="fa fa-check"></i><b>2</b> Estadística descriptiva</a><ul>
<li class="chapter" data-level="2.1" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#tendencia-central"><i class="fa fa-check"></i><b>2.1</b> Tendencia central</a><ul>
<li class="chapter" data-level="2.1.1" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#mínimo-y-máximo"><i class="fa fa-check"></i><b>2.1.1</b> Mínimo y máximo</a></li>
<li class="chapter" data-level="2.1.2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#media"><i class="fa fa-check"></i><b>2.1.2</b> Media</a></li>
<li class="chapter" data-level="2.1.3" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#mediana"><i class="fa fa-check"></i><b>2.1.3</b> Mediana</a></li>
<li class="chapter" data-level="2.1.4" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#primer-y-tercer-cuartil"><i class="fa fa-check"></i><b>2.1.4</b> Primer y tercer cuartil</a></li>
<li class="chapter" data-level="2.1.5" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#moda"><i class="fa fa-check"></i><b>2.1.5</b> Moda</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#dispersión"><i class="fa fa-check"></i><b>2.2</b> Dispersión</a><ul>
<li class="chapter" data-level="2.2.1" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#rango"><i class="fa fa-check"></i><b>2.2.1</b> Rango</a></li>
<li class="chapter" data-level="2.2.2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#desviación-estándard"><i class="fa fa-check"></i><b>2.2.2</b> Desviación estándard</a></li>
<li class="chapter" data-level="2.2.3" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#varianza"><i class="fa fa-check"></i><b>2.2.3</b> Varianza</a></li>
<li class="chapter" data-level="2.2.4" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#coeficiente-de-variación"><i class="fa fa-check"></i><b>2.2.4</b> Coeficiente de variación</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#correlación"><i class="fa fa-check"></i><b>2.3</b> Correlación</a><ul>
<li class="chapter" data-level="2.3.1" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#datos"><i class="fa fa-check"></i><b>2.3.1</b> Datos</a></li>
<li class="chapter" data-level="2.3.2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#coeficiente-de-correlación"><i class="fa fa-check"></i><b>2.3.2</b> Coeficiente de correlación</a></li>
<li class="chapter" data-level="2.3.3" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#test-de-correlación"><i class="fa fa-check"></i><b>2.3.3</b> Test de correlación</a></li>
<li class="chapter" data-level="2.3.4" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#visualizando-correlaciones"><i class="fa fa-check"></i><b>2.3.4</b> Visualizando correlaciones</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#ejercicios-1"><i class="fa fa-check"></i><b>2.4</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html"><i class="fa fa-check"></i><b>3</b> Estadística inferencial</a><ul>
<li class="chapter" data-level="3.1" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#diferencia-entre-probabilidad-y-estadística"><i class="fa fa-check"></i><b>3.1</b> Diferencia entre probabilidad y estadística</a></li>
<li class="chapter" data-level="3.2" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#probabilidad-frecuentista-vs-bayesiana"><i class="fa fa-check"></i><b>3.2</b> Probabilidad frecuentista vs Bayesiana</a><ul>
<li class="chapter" data-level="3.2.1" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#enfoque-frecuentista"><i class="fa fa-check"></i><b>3.2.1</b> Enfoque frecuentista</a></li>
<li class="chapter" data-level="3.2.2" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#enfoque-bayesiano"><i class="fa fa-check"></i><b>3.2.2</b> Enfoque Bayesiano</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#introducción-a-las-distribuciones-de-probabilidad"><i class="fa fa-check"></i><b>3.3</b> Introducción a las distribuciones de probabilidad</a><ul>
<li class="chapter" data-level="3.3.1" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#la-distribución-binomial"><i class="fa fa-check"></i><b>3.3.1</b> La distribución binomial</a></li>
<li class="chapter" data-level="3.3.2" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#la-distribución-normal"><i class="fa fa-check"></i><b>3.3.2</b> La distribución normal</a></li>
<li class="chapter" data-level="3.3.3" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#funciones-de-r-para-distribuciones-de-probabilidad"><i class="fa fa-check"></i><b>3.3.3</b> Funciones de R para distribuciones de probabilidad</a></li>
<li class="chapter" data-level="3.3.4" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#ejemplos-con-la-distribución-binomial"><i class="fa fa-check"></i><b>3.3.4</b> Ejemplos con la distribución Binomial</a></li>
<li class="chapter" data-level="3.3.5" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#ejemplos-con-la-distribución-normal"><i class="fa fa-check"></i><b>3.3.5</b> Ejemplos con la distribución normal</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#introduccion-a-los-test-de-hipótesis"><i class="fa fa-check"></i><b>3.4</b> Introduccion a los test de hipótesis</a><ul>
<li class="chapter" data-level="3.4.1" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#comparando-la-estadística-de-prueba-con-el-valor-crítico."><i class="fa fa-check"></i><b>3.4.1</b> Comparando la estadística de prueba con el <strong>valor crítico</strong>.</a></li>
<li class="chapter" data-level="3.4.2" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#comparando-el-p-valor-con-el-nivel-de-significancia-alpha"><i class="fa fa-check"></i><b>3.4.2</b> Comparando el <em>p</em>-valor con el nivel de significancia <span class="math inline">\(\alpha\)</span></a></li>
<li class="chapter" data-level="3.4.3" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#comparación-del-parámetro-objetivo-con-el-intervalo-de-confianza"><i class="fa fa-check"></i><b>3.4.3</b> Comparación del parámetro objetivo con el intervalo de confianza</a></li>
<li class="chapter" data-level="3.4.4" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#errortypes"><i class="fa fa-check"></i><b>3.4.4</b> Dos tipos de errores</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#test-de-hipótesis-en-r-cálculo-e-informes"><i class="fa fa-check"></i><b>3.5</b> Test de hipótesis en R: cálculo e informes</a></li>
<li class="chapter" data-level="3.6" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#un-ejemplo-sobre-brecha-salarial-entre-géneros"><i class="fa fa-check"></i><b>3.6</b> Un ejemplo sobre brecha salarial entre géneros</a></li>
<li class="chapter" data-level="3.7" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#anova"><i class="fa fa-check"></i><b>3.7</b> ANOVA</a></li>
<li class="chapter" data-level="3.8" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#algunas-consideraciones-finales"><i class="fa fa-check"></i><b>3.8</b> Algunas consideraciones finales</a><ul>
<li class="chapter" data-level="3.8.1" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#cuando-no-se-necesita-inferencia"><i class="fa fa-check"></i><b>3.8.1</b> ¿Cuando no se necesita inferencia?</a></li>
<li class="chapter" data-level="3.8.2" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#problemas-con-los-p-valores"><i class="fa fa-check"></i><b>3.8.2</b> Problemas con los p-valores</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#ejercicios-2"><i class="fa fa-check"></i><b>3.9</b> Ejercicios</a><ul>
<li class="chapter" data-level="3.9.1" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#distribución-binomial"><i class="fa fa-check"></i><b>3.9.1</b> Distribución Binomial</a></li>
<li class="chapter" data-level="3.9.2" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#distribución-normal"><i class="fa fa-check"></i><b>3.9.2</b> Distribución Normal</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="el-muestreo-estadístico.html"><a href="el-muestreo-estadístico.html"><i class="fa fa-check"></i><b>4</b> El muestreo estadístico</a><ul>
<li class="chapter" data-level="4.1" data-path="el-muestreo-estadístico.html"><a href="el-muestreo-estadístico.html#example-one"><i class="fa fa-check"></i><b>4.1</b> Example one</a></li>
<li class="chapter" data-level="4.2" data-path="el-muestreo-estadístico.html"><a href="el-muestreo-estadístico.html#example-two"><i class="fa fa-check"></i><b>4.2</b> Example two</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>5</b> Regresión lineal</a><ul>
<li class="chapter" data-level="5.1" data-path="regression.html"><a href="regression.html#intro-regression"><i class="fa fa-check"></i><b>5.1</b> ¿Qué es un modelo de regresión lineal?</a></li>
<li class="chapter" data-level="5.2" data-path="regression.html"><a href="regression.html#regressionestimation"><i class="fa fa-check"></i><b>5.2</b> Estimación de un modelo de regresión lineal</a><ul>
<li class="chapter" data-level="5.2.1" data-path="regression.html"><a href="regression.html#lm"><i class="fa fa-check"></i><b>5.2.1</b> Usando la función <code>lm ()</code></a></li>
<li class="chapter" data-level="5.2.2" data-path="regression.html"><a href="regression.html#interpretación-del-modelo-estimado"><i class="fa fa-check"></i><b>5.2.2</b> Interpretación del modelo estimado</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="regression.html"><a href="regression.html#multipleregression"><i class="fa fa-check"></i><b>5.3</b> Regresión lineal múltiple</a><ul>
<li class="chapter" data-level="5.3.1" data-path="regression.html"><a href="regression.html#haciéndolo-en-r"><i class="fa fa-check"></i><b>5.3.1</b> Haciéndolo en R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="estadística-multivariante.html"><a href="estadística-multivariante.html"><i class="fa fa-check"></i><b>6</b> Estadística multivariante</a></li>
<li class="chapter" data-level="" data-path="referencias.html"><a href="referencias.html"><i class="fa fa-check"></i>Referencias</a></li>
<li class="divider"></li>
<li><a href="https://github.com/geourv/quanti" target="blank">Publicado con bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Técnicas cuantitativas</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="estadística-descriptiva" class="section level1">
<h1><span class="header-section-number">Capítulo 2</span> Estadística descriptiva</h1>
<!-- https://bookdown.org/mikemahoney218/IDEAR/basic-statistics-using-r.html -->
<!-- https://statsandr.com/blog/descriptive-statistics-in-r/#first-and-third-quartile -->
<p>La estadística descriptiva es una rama de la estadística cuyo objetivo es resumir, describir y presentar una serie de valores o un conjunto de datos. Estas estadísticas pueden ser realmente útiles al analizar largas series de datos en las que resulte difícil reconocer algún patrón. En éste capítulo utilizaremos una muestra de datos sobre salarios (en euros) de una <em>población</em> de 100 trabajadores:</p>
<p><em>2186</em>, <em>1218</em>, <em>1682</em>, <em>1816</em>, <em>1702</em>, <em>1447</em>, <em>2256</em>, <em>1453</em>, <em>2509</em>, <em>1469</em>, <em>2152</em>, <em>2643</em>, <em>806</em>, <em>1361</em>, <em>1433</em>, <em>1818</em>, <em>1358</em>, <em>172</em>, <em>280</em>, <em>2160</em>, <em>1347</em>, <em>609</em>, <em>1414</em>, <em>2107</em>, <em>2448</em>, <em>1285</em>, <em>1371</em>, <em>618</em>, <em>1730</em>, <em>1180</em>, <em>1728</em>, <em>1852</em>, <em>2018</em>, <em>1196</em>, <em>1752</em>, <em>642</em>, <em>1108</em>, <em>1074</em>, <em>293</em>, <em>1518</em>, <em>1603</em>, <em>1320</em>, <em>1879</em>, <em>1137</em>, <em>816</em>, <em>1716</em>, <em>1094</em>, <em>2222</em>, <em>1284</em>, <em>1828</em>, <em>1661</em>, <em>1108</em>, <em>2288</em>, <em>1821</em>, <em>1545</em>, <em>1638</em>, <em>1840</em>, <em>1545</em>, <em>4</em>, <em>1642</em>, <em>1316</em>, <em>1593</em>, <em>1791</em>, <em>2200</em>, <em>1136</em>, <em>2151</em>, <em>1668</em>, <em>2019</em>, <em>1960</em>, <em>1860</em>, <em>978</em>, <em>1455</em>, <em>1812</em>, <em>1023</em>, <em>1229</em>, <em>1790</em>, <em>1884</em>, <em>1732</em>, <em>1057</em>, <em>950</em>, <em>2256</em>, <em>1629</em>, <em>1544</em>, <em>1440</em>, <em>903</em>, <em>1806</em>, <em>1391</em>, <em>1409</em>, <em>1967</em>, <em>1911</em>, <em>2196</em>, <em>1262</em>, <em>1825</em>, <em>2196</em>, <em>945</em>, <em>1070</em>, <em>934</em>, <em>770</em>, <em>1540</em> y <em>1827</em></p>
<p>De un primer vistazo es difícil (por no decir imposible) que podamos comprender los datos y tener una visión clara de los salarios de este grupo de personas. Las estadísticas descriptivas permiten resumir y así tener una mejor visión general de los datos. Por supuesto, al resumir los datos a través de una o varias medidas, inevitablemente se perderá parte de la información. Sin embargo, en muchos casos es mejor perder algo de información pero, a cambio, obtener una visión general. Podriamos decir que se trata de <em>ganar perspectiva</em>.</p>
<p>La estadística descriptiva es a menudo el primer paso y una parte importante en cualquier análisis estadístico. Permite comprobar la calidad de los datos detectando posibles valores atípicos (<em>outliers</em>), es decir, datos que parecen ser significativamente distintos del resto. También se puede utilizar estadística descriptiva para detectar errores de recopilación o codificación, determinar si están bien presentados, entre otras posibles aplicaciones.</p>
<p>Podemos distinguir dos típos básicos de estadísticos para describir un conjunto de datos: de centralidad y de dispersión. Habitualmente, ambos tipos de medidas se utilizan juntos para resumir los datos de la forma más concisa.</p>
<div id="tendencia-central" class="section level2">
<h2><span class="header-section-number">2.1</span> Tendencia central</h2>
<p>Las medidas de tendencia central permiten ver “dónde” se ubican los datos, alrededor de qué valores. En otras palabras, las medidas de ubicación permiten comprender cuál es la tendencia central o la “posición” de los datos en su conjunto. Entre las estadísticas más habituales de este tipo podemos distinguir:</p>
<ul>
<li>Mínimo y máximo</li>
<li>Media</li>
<li>Mediana</li>
<li>Primer y tercer cuartil</li>
<li>Moda</li>
</ul>
<div id="mínimo-y-máximo" class="section level3">
<h3><span class="header-section-number">2.1.1</span> Mínimo y máximo</h3>
<p>Mínimo (<span class="math inline">\(min\)</span>) y máximo (<span class="math inline">\(max\)</span>) son simplemente los valores más bajo y más alto de la muestra. Dada una muestra de 6 de estos salarios:</p>
<p><em>2186</em>, <em>1218</em>, <em>1682</em>, <em>1816</em>, <em>1702</em> y <em>1447</em></p>
<p>El mínimo es 1217.7 euros y el máximo es 2185.5 euros. Estas dos estadísticas básicas dan una idea clara sobre el los extremos de la muestra y su cálculo con R es bastante sencillo:</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="estadística-descriptiva.html#cb84-1"></a><span class="kw">min</span>(salarios_sel)</span></code></pre></div>
<pre><code>## [1] 1217.7</code></pre>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="estadística-descriptiva.html#cb86-1"></a><span class="kw">max</span>(salarios_sel)</span></code></pre></div>
<pre><code>## [1] 2185.5</code></pre>
</div>
<div id="media" class="section level3">
<h3><span class="header-section-number">2.1.2</span> Media</h3>
<p>La media o promedio, es probablemente la estadística más habitual. Da una idea de cuál es el valor medio, es decir, el valor central de los datos o, en otras palabras, su centro de gravedad. La media se encuentra sumando todos los valores y dividiendo esta suma por el número de observaciones (<span class="math inline">\(n\)</span>):</p>
<p><span class="math display">\[Media =\overline{x}=\frac{\text{suma de todos los valores}}{\text{número de valores}} = \frac{1}{n}\sum^{n}_{i=1}x_i\]</span>
Dada nuestra muestra de 6 salarios presentada anteriormente, la media es:</p>
<p><span class="math display">\[\overline{x} = \frac{2186 + 1218 + 1682 + 1816 + 1702 + 1447}{6}= 1675,033\]</span></p>
<p>En conclusión, el tamaño medio de la nuestra muestra es 1675.03 euros (redondeado a 2 decimales). El cálculo con R también resulta bastante sencillo:</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="estadística-descriptiva.html#cb88-1"></a><span class="kw">mean</span>(salarios_sel)</span></code></pre></div>
<pre><code>## [1] 1675.033</code></pre>
</div>
<div id="mediana" class="section level3">
<h3><span class="header-section-number">2.1.3</span> Mediana</h3>
<p>La mediana es otra medida de centralidad. La interpretación de la mediana es que hay tantas observaciones por debajo como por encima de la mediana. En otras palabras, el 50% de las observaciones se encuentran por debajo de la mediana y el 50% de las observaciones están por encima de la mediana.</p>
<p>La forma más fácil de calcular la mediana es primero ordenar los datos de menor a mayor (es decir, en orden ascendente) y luego tomar el punto medio como la mediana. A partir de los valores ordenados, para un número impar de observaciones, el punto medio es fácil de encontrar: es el valor con tantas observaciones abajo como arriba. Aún a partir de los valores ordenados, para un número par de observaciones, el punto medio está exactamente entre los dos valores medios. Formalmente, después de ordenar, la mediana es:</p>
<ul>
<li>si <span class="math inline">\(n\)</span> (número de observaciones) es impar: <span class="math display">\[mediana(x) = x_{\frac{n + 1}{2}}\]</span></li>
<li>si <span class="math inline">\(n\)</span> es par: <span class="math display">\[mediana(x) = \frac{1}{2}\big(x_{\frac{n}{2}} + x_{\frac{n}{2} + 1} \big)\]</span></li>
</ul>
<p>donde el subíndice de <span class="math inline">\(x\)</span> denota la numeración de los datos ordenados. El cálculo en R es de nuevo bastante sencillo:</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="estadística-descriptiva.html#cb90-1"></a><span class="kw">median</span>(salarios_sel)</span></code></pre></div>
<pre><code>## [1] 1691.85</code></pre>
</div>
<div id="primer-y-tercer-cuartil" class="section level3">
<h3><span class="header-section-number">2.1.4</span> Primer y tercer cuartil</h3>
<p>El primer y tercer cuartil son similares a la mediana en el sentido de que también dividen las observaciones en dos partes, solo que estas partes no son iguales. Recordad que la mediana divide los datos en dos partes iguales (con el 50% de las observaciones por debajo y el 50% por encima de la mediana). El primer cuartil divide las observaciones de modo que haya un 25% de las observaciones <em>debajo de</em> este punto y un 75% <strong>por encima</strong> del primer cuartil. El tercer cuartil se calcula del mismo modo pero representa el valor con el 75% de las observaciones por debajo y el 25% de las observaciones por encima. Existen varios métodos para calcular el primer y tercer cuartil, pero por ejemplo se puede calcular siguiendo los siguientes pasos:</p>
<ol style="list-style-type: decimal">
<li>Ordenar los datos en orden ascendente</li>
<li>Calcular <span class="math inline">\(0.25\cdot n\)</span> y <span class="math inline">\(0.75\cdot n\)</span> (es decir, 0.25 y 0.75 veces el número de observaciones)</li>
<li>Redondear estos dos números al siguiente número entero <code>ceil</code></li>
</ol>
<p>Los pasos son los mismos para un número par e impar de observaciones. A continuación se muestra un ejemplo para el cálculo de estos valores sobre los salarios de nueve trabajadores:</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="estadística-descriptiva.html#cb92-1"></a><span class="kw">quantile</span>(salarios_sel)</span></code></pre></div>
<pre><code>##       0%      25%      50%      75%     100% 
## 1217.700 1505.575 1691.850 1787.825 2185.500</code></pre>
<p>Dado que obtenemos un vector de resultados, podemos seleccionar por posición para obtener el que necesitemos en cada caso.</p>
</div>
<div id="moda" class="section level3">
<h3><span class="header-section-number">2.1.5</span> Moda</h3>
<p>La moda de una serie es el valor que aparece con mayor frecuencia. En otras palabras, es el valor que tiene el mayor número de ocurrencias. Dados los siguientes salarios:</p>
<p><em>1700</em>, <em>1680</em>, <em>1710</em>, <em>1700</em>, <em>1820</em>, <em>1650</em>, <em>1700</em>, <em>1890</em> y <em>1670</em></p>
<p>La moda es 1700 porque es el valor más común con 3 apariciones. Todos los demás valores aparecen solo una vez. En conclusión, la mayoría de los trabajadores de esta muestra perciben exactamente 1700 euros al mes.</p>
<p>Hay que tener en cuenta que es posible que una serie no tenga moda (p. Ej., <em>4</em>, <em>7</em>, <em>2</em> y <em>10</em>) o más de una moda (p. Ej., <em>4</em>, <em>2</em>, <em>2</em>, <em>8</em>, <em>11</em> y <em>11</em>). Los datos con dos modas a menudo se denominan bimodales y los datos con más de dos modos a menudo se denominan multimodales, a diferencia de las series con una moda, que se denominan unimodales.</p>
<p>A diferencia de las anteriores estadísticas (mínimo, máximo, media, mediana, primer y tercer cuartil) que solo se pueden calcular para variables cuantitativas, <strong>la moda se puede calcular para variables cuantitativas y cualitativas</strong>. Atendiendo al tipo de empleo que desarrollan los 9 trabajadores presentados anteriormente:</p>
<p><em>ingeniero</em>, <em>ingeniero</em>, <em>ingeniero</em>, <em>ingeniero</em>, <em>asistente</em>, <em>asistente</em>, <em>asistente</em>, <em>ingeniero</em> y <em>camarero</em></p>
<p>La moda es “ingeniero”, por lo que la mayoría de los trabajadores de esta muestra son de uso ingenieros.</p>
</div>
</div>
<div id="dispersión" class="section level2">
<h2><span class="header-section-number">2.2</span> Dispersión</h2>
<div id="rango" class="section level3">
<h3><span class="header-section-number">2.2.1</span> Rango</h3>
<p>El rango es la diferencia entre el máximo y el mínimo:</p>
<p><span class="math display">\[rango = max - min\]</span></p>
<p>Dada nuestra muestra de salarios:</p>
<p><em>2186</em>, <em>1218</em>, <em>1682</em>, <em>1816</em>, <em>1702</em> y <em>1447</em></p>
<p>El rango es 2185.5 <span class="math inline">\(-\)</span> 1217.7 <span class="math inline">\(=\)</span> 967.8 euros. El rango es muy sencillo de calcular y en algunos casos puede dar una buena idea de lo que podemos esperar de un conjunto de datos. En R se puede utilizar la función <code>range</code></p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="estadística-descriptiva.html#cb94-1"></a><span class="kw">range</span>(salarios_sel)</span></code></pre></div>
<pre><code>## [1] 1217.7 2185.5</code></pre>
<p>No obstante, esta métrica no da ninguna información de la distribución interna del resto de medidas.</p>
</div>
<div id="desviación-estándard" class="section level3">
<h3><span class="header-section-number">2.2.2</span> Desviación estándard</h3>
<p>La desviación estándar es la medida de dispersión más común en estadística. Si tenemos que presentar una estadística que resuma la distribución de los datos, suele ser la desviación estándar. Como sugiere su nombre, la desviación estándar indica cuál es la desviación <em>normal</em> de los datos. De hecho, calcula la desviación promedio de la <strong>media</strong>. Cuanto mayor sea la desviación estándar, más dispersos estarán los datos. Por el contrario, cuanto menor es la desviación estándar, más se centran los datos alrededor de la media.</p>
<p>Existen dos fórmulas para calcular la desviación estándard en función de si nos enfrentamos a una muestra o a una población. Una población incluye a todos los miembros de un grupo específico, mientras que una muestra contiene algunas observaciones extraídas de la población, es decir, una parte o un subconjunto de la población. Por ejemplo, la población puede ser “<strong>todas</strong> personas que viven en España” y la muestra puede ser “<strong>algunas</strong> personas que viven en España”.</p>
<p>La desviación estándar para una población, a partir de ahora <span class="math inline">\(\sigma\)</span>, es:</p>
<p><span class="math display">\[\sigma = \sqrt{\frac{1}{n}\sum^n_{i = 1}(x_i - \mu)^2}\]</span>
Como se puede ver en la fórmula, la desviación estándar es en realidad la desviación promedio de los datos de su media <span class="math inline">\(\mu\)</span>. Hay calcular primero el cuadrado de la diferencia entre las observaciones y la media para evitar que las diferencias negativas se compensen con diferencias positivas.</p>
<p>Por ejemplo, imagine una población de solo 3 trabajadores:</p>
<p><em>770</em>, <em>1540</em> y <em>1827</em></p>
<p>La media es 1379 (redondeado a 1 decimal). La desviación estándar es entonces:</p>
<p><span class="math display">\[\sigma = \sqrt{\frac{1}{3}\big[(770.4 - 1379)^2 + (1540 - 1379)^2 + (1827 - 1379)^2 \big]}\]</span>
<span class="math display">\[\sigma = 546,2\]</span></p>
<p>Por lo tanto, la desviación estándar para los salarios de estos trabajadores es de 546,2 euros. Esto significa que los salarios de los trabajadores de esta población se desvían de la media en 546,2 euros.</p>
<p>…</p>
</div>
<div id="varianza" class="section level3">
<h3><span class="header-section-number">2.2.3</span> Varianza</h3>
</div>
<div id="coeficiente-de-variación" class="section level3">
<h3><span class="header-section-number">2.2.4</span> Coeficiente de variación</h3>
</div>
</div>
<div id="correlación" class="section level2">
<h2><span class="header-section-number">2.3</span> Correlación</h2>
<p>Las correlaciones entre variables juegan un papel importante en un <strong>análisis descriptivo</strong>. Una correlación mide la <strong>relación entre dos variables</strong>, es decir, cómo están vinculadas entre sí. En este sentido, una correlación permite saber si dos variables evolucionan en la misma dirección, en sentido contrario y si son independientes.</p>
<p>En este capítulo, se muestra cómo calcular <strong>coeficientes de correlación</strong>, cómo realizar <strong>pruebas de correlación</strong> y cómo <strong>visualizar</strong> correlaciones entre variables usando R.</p>
<p>La correlación generalmente se calcula en dos variables <em>cuantitativas</em>, pero también se puede calcular en dos variables <em>cualitativas ordinales</em> (ver prueba de independencia de chi-cuadrado).</p>
<div id="datos" class="section level3">
<h3><span class="header-section-number">2.3.1</span> Datos</h3>
<p>Usaremos el conjunto de datos <code>mtcars</code>. Este conjunto de datos viene cargado por defecto en R, de modo que se utiliza en numerosas demostraciones.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="estadística-descriptiva.html#cb96-1"></a><span class="co"># mostrar las primeras cinco filas</span></span>
<span id="cb96-2"><a href="estadística-descriptiva.html#cb96-2"></a><span class="kw">head</span>(mtcars, <span class="dv">5</span>)</span></code></pre></div>
<pre><code>##                    mpg cyl disp  hp drat    wt  qsec vs am gear carb
## Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
## Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
## Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
## Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
## Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2</code></pre>
<p>Las variables <code>vs</code> y<code>am</code> son variables categóricas, por lo que se eliminan para este artículo:</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="estadística-descriptiva.html#cb98-1"></a><span class="co"># Eliminar las variables vs y am</span></span>
<span id="cb98-2"><a href="estadística-descriptiva.html#cb98-2"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb98-3"><a href="estadística-descriptiva.html#cb98-3"></a>dat &lt;-<span class="st"> </span>mtcars <span class="op">%&gt;%</span></span>
<span id="cb98-4"><a href="estadística-descriptiva.html#cb98-4"></a><span class="kw">select</span>(<span class="op">-</span>vs, <span class="op">-</span>am)</span>
<span id="cb98-5"><a href="estadística-descriptiva.html#cb98-5"></a></span>
<span id="cb98-6"><a href="estadística-descriptiva.html#cb98-6"></a><span class="co"># mostrar las primeras cinco filas</span></span>
<span id="cb98-7"><a href="estadística-descriptiva.html#cb98-7"></a><span class="kw">head</span>(dat, <span class="dv">5</span>)</span></code></pre></div>
<pre><code>##                    mpg cyl disp  hp drat    wt  qsec gear carb
## Mazda RX4         21.0   6  160 110 3.90 2.620 16.46    4    4
## Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02    4    4
## Datsun 710        22.8   4  108  93 3.85 2.320 18.61    4    1
## Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44    3    1
## Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02    3    2</code></pre>
</div>
<div id="coeficiente-de-correlación" class="section level3">
<h3><span class="header-section-number">2.3.2</span> Coeficiente de correlación</h3>
<p>La correlación entre 2 variables se calcula con la función <code>cor()</code>. Supón que queremos calcular la correlación entre caballos de potencia (<code>hp</code>) y millas por galón (<code>mpg</code>):</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="estadística-descriptiva.html#cb100-1"></a><span class="co"># Correlación de Pearson entre 2 variables </span></span>
<span id="cb100-2"><a href="estadística-descriptiva.html#cb100-2"></a><span class="kw">cor</span>(dat<span class="op">$</span>hp, dat<span class="op">$</span>mpg)</span></code></pre></div>
<pre><code>## [1] -0.7761684</code></pre>
<p>Hay que fijarse en que la correlación entre las variables <em>X</em> e <em>Y</em> es igual a la correlación entre las variables <em>Y</em> y <em>X</em>, por lo que el orden de las variables en la función <code>cor()</code> no importa.</p>
<p>La función <code>cor()</code> calcula por defecto la correlación de Pearson, por lo que si se quiere calcular la correlación por otro método, se puede agregar el argumento <code>method =" spearman "</code> a la función <code>cor()</code>:</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="estadística-descriptiva.html#cb102-1"></a><span class="co"># Correlación de Sperman entre 2 variables </span></span>
<span id="cb102-2"><a href="estadística-descriptiva.html#cb102-2"></a><span class="kw">cor</span>(dat<span class="op">$</span>hp, dat<span class="op">$</span>mpg,</span>
<span id="cb102-3"><a href="estadística-descriptiva.html#cb102-3"></a>    <span class="dt">method =</span> <span class="st">&quot;spearman&quot;</span>)</span></code></pre></div>
<pre><code>## [1] -0.8946646</code></pre>
<p>Hay varios métodos de correlación (se puede consultar la ayuda de la la función para saber más <code>?cor</code>):</p>
<ul>
<li><strong>Pearson</strong> se usa a menudo para variables <em>cuantitativas continuas</em> que tienen una relación lineal.</li>
<li><strong>Spearman</strong> (es similar a Pearson pero se basa en los valores ordenados para cada variable en lugar de en los datos brutos) se usa a menudo para evaluar relaciones que involucran variables cualitativas ordinales en las que la relación sea parcialmente lineal.</li>
<li><strong>Kendall</strong> se calcula a partir del número de pares concordantes y discordantes, se utiliza a menudo para variables ordinales cualitativas.</li>
</ul>
<p>La función <code>cor ()</code> también permite calcular correlaciones para varios pares de variables a la vez:</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="estadística-descriptiva.html#cb104-1"></a><span class="co"># Correlaciones entre todas las variables</span></span>
<span id="cb104-2"><a href="estadística-descriptiva.html#cb104-2"></a><span class="kw">round</span>(<span class="kw">cor</span>(dat),</span>
<span id="cb104-3"><a href="estadística-descriptiva.html#cb104-3"></a>      <span class="dt">digits =</span> <span class="dv">2</span> <span class="co"># redondeo a dos decimales</span></span>
<span id="cb104-4"><a href="estadística-descriptiva.html#cb104-4"></a>      ) </span></code></pre></div>
<pre><code>##        mpg   cyl  disp    hp  drat    wt  qsec  gear  carb
## mpg   1.00 -0.85 -0.85 -0.78  0.68 -0.87  0.42  0.48 -0.55
## cyl  -0.85  1.00  0.90  0.83 -0.70  0.78 -0.59 -0.49  0.53
## disp -0.85  0.90  1.00  0.79 -0.71  0.89 -0.43 -0.56  0.39
## hp   -0.78  0.83  0.79  1.00 -0.45  0.66 -0.71 -0.13  0.75
## drat  0.68 -0.70 -0.71 -0.45  1.00 -0.71  0.09  0.70 -0.09
## wt   -0.87  0.78  0.89  0.66 -0.71  1.00 -0.17 -0.58  0.43
## qsec  0.42 -0.59 -0.43 -0.71  0.09 -0.17  1.00 -0.21 -0.66
## gear  0.48 -0.49 -0.56 -0.13  0.70 -0.58 -0.21  1.00  0.27
## carb -0.55  0.53  0.39  0.75 -0.09  0.43 -0.66  0.27  1.00</code></pre>
<p>La correlación varía de <strong>-1 a 1</strong>, de modo que el signo nos indica la dirección de la relación (aumentan a la vez o son opuestas) y el valor nos indica la fuerza de la relación (más fuerte cuanto más alejado de 0).</p>
<p>Una <strong>correlación negativa</strong> implica que las dos variables consideradas varían en <strong>direcciones opuestas</strong>, es decir, si una variable aumenta la otra disminuye y viceversa. Por otro lado, una <strong>correlación positiva</strong> implica que las dos variables consideradas varían en la <strong>misma dirección</strong>, es decir, si una variable aumenta, la otra aumenta y si una disminuye, la otra también disminuye.</p>
<p>En cuanto a la fuerza de la relación: cuanto <strong>más extremo</strong> es el coeficiente de correlación (cuanto más cerca de -1 o 1), <strong>más fuerte es la relación</strong>. Esto también significa que una <strong>correlación cercana a 0</strong> indica que las dos variables son <strong>independientes</strong>, es decir, a medida que una variable aumenta, no hay tendencia en la otra variable a disminuir o aumentar.</p>
<p>Por ejemplo, la correlación de Pearson entre caballos de potencia (<code>hp</code>) y millas por galón (<code>mpg</code>) encontrada es -0.78, lo que significa que las 2 variables varían en dirección opuesta. Esto tiene sentido, los automoviles con más caballos de potencia suelen a consumir más combustible (hacen menos millas con el mismo combustible que los automóviles más potentes). Por el contrario, de la matriz de correlación vemos que la correlación entre millas por galón (<code>mpg</code>) y el tiempo para conducir un cuarto de milla (<code>qsec</code>) es 0.42, lo que significa que los automóviles rápidos (con un menor <code>qsec</code>) tienden a tener un peor rendimiento por galón (bajo <code>mpg</code>). De nuevo, esto tiene sentido, ya que los coches rápidos tienden a consumir más combustible.</p>
</div>
<div id="test-de-correlación" class="section level3">
<h3><span class="header-section-number">2.3.3</span> Test de correlación</h3>
<blockquote>
<p>Volver una vez leída la sección sobre test de hipótesis.</p>
</blockquote>
<p>Hay que tener en cuenta que el valor <em>p</em> se basa en el coeficiente de correlación y en el tamaño de la muestra. Cuanto mayor sea el tamaño de la muestra y más extrema será la correlación (más cercana a -1 o 1). Con un tamaño de muestra pequeño, es posible obtener una correlación <em>relativamente</em> grande en la muestra (según el coeficiente de correlación), pero aún así encontrar una correlación no significativamente diferente de 0 en la población (según la prueba de correlación). Por este motivo, se recomienda realizar siempre un test de correlación antes de interpretar un coeficiente de correlación para evitar conclusiones erróneas.</p>
<p>A diferencia de una matriz de correlación que indica los coeficientes de correlación entre algunos pares de variables en la muestra, se utiliza un test de correlación para probar si la correlación (<span class="math inline">\(\rho\)</span>) entre dos variables es significativamente diferente de 0 o no en la <em>población</em>.</p>
<p>En realidad, un coeficiente de correlación diferente de 0 en la muestra no significa que la correlación sea <strong>significativamente</strong> diferente de 0 en la población. Esto debe probarse con un <strong>test de hipótesis</strong>.</p>
<p>Las hipótesis (nula y alternativa) para el test de correlación son las siguientes:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\rho = 0\)</span> (si no existe una relación lineal entre las dos variables)</li>
<li><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\rho\ne 0\)</span> (si existe una relación lineal entre las dos variables)</li>
</ul>
<p>A través de esta prueba de correlación, lo que realmente estamos probando es si:</p>
<ul>
<li>La muestra contiene evidencia suficiente para rechazar la hipótesis nula y concluir que el coeficiente de correlación no es igual a 0, por lo que la relación existe en la población.</li>
<li>La muestra no contiene suficiente evidencia de que el coeficiente de correlación no sea igual a 0, por lo que en este caso no rechazamos la hipótesis nula de no-relación entre las variables de la población.</li>
</ul>
<p>Supongamos que queremos probar si el ratio del eje trasero (<code>drat</code>) está correlacionado con el tiempo necesario para conducir 1/4 de milla (<code>qsec</code>):</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="estadística-descriptiva.html#cb106-1"></a><span class="co"># Test de correlación de Pearson</span></span>
<span id="cb106-2"><a href="estadística-descriptiva.html#cb106-2"></a>test &lt;-<span class="st"> </span><span class="kw">cor.test</span>(dat<span class="op">$</span>drat, dat<span class="op">$</span>qsec)</span>
<span id="cb106-3"><a href="estadística-descriptiva.html#cb106-3"></a>test</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  dat$drat and dat$qsec
## t = 0.50164, df = 30, p-value = 0.6196
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.265947  0.426340
## sample estimates:
##        cor 
## 0.09120476</code></pre>
<p>El <em>p</em>-valor de la prueba de correlación entre estas 2 variables es 0.62. Al nivel de significancia del 5%, no se rechaza la hipótesis nula de no correlación. Por lo tanto, concluimos que no rechazamos la hipótesis de que no existe una relación lineal entre las 2 variables.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a></p>
<p>Esta prueba demuestra que incluso si el coeficiente de correlación es diferente de 0 (la correlación es 0.09 en la muestra), en realidad no es significativamente diferente de 0 en la población.</p>
</div>
<div id="visualizando-correlaciones" class="section level3">
<h3><span class="header-section-number">2.3.4</span> Visualizando correlaciones</h3>
<p>Una buena forma de visualizar una correlación entre 2 variables es mediante un diagrama de dispersión. Por ejemplo:</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="estadística-descriptiva.html#cb108-1"></a><span class="co"># Diagrama de dispersión con R base</span></span>
<span id="cb108-2"><a href="estadística-descriptiva.html#cb108-2"></a><span class="kw">plot</span>(dat<span class="op">$</span>hp, dat<span class="op">$</span>mpg)</span></code></pre></div>
<p><img src="tecnicas-cuantitativas_files/figure-html/unnamed-chunk-45-1.png" width="672" /></p>
<p>Para visualizar la relación entre más de 2 variablesse puede usar la función <code>pair ()</code>. En este caso limitamos el ejemplo a tres variables:</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="estadística-descriptiva.html#cb109-1"></a><span class="co"># Multiples diagramas de dispersión</span></span>
<span id="cb109-2"><a href="estadística-descriptiva.html#cb109-2"></a><span class="kw">pairs</span>(dat[, <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">4</span>, <span class="dv">6</span>)])</span></code></pre></div>
<p><img src="tecnicas-cuantitativas_files/figure-html/unnamed-chunk-46-1.png" width="672" /></p>
<p>Por otra parte, existen numerosas librerías de R que permiten generar este tipo de gráficos con distintas opciones. Por ejemplo con <code>ggplot2</code>:</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="estadística-descriptiva.html#cb110-1"></a><span class="co"># Diagrama de dispersión con ggplot2</span></span>
<span id="cb110-2"><a href="estadística-descriptiva.html#cb110-2"></a><span class="kw">library</span>(ggplot2)</span>
<span id="cb110-3"><a href="estadística-descriptiva.html#cb110-3"></a></span>
<span id="cb110-4"><a href="estadística-descriptiva.html#cb110-4"></a><span class="kw">ggplot</span>(dat) <span class="op">+</span></span>
<span id="cb110-5"><a href="estadística-descriptiva.html#cb110-5"></a><span class="st"> </span><span class="kw">aes</span>(<span class="dt">x =</span> hp, <span class="dt">y =</span> mpg) <span class="op">+</span></span>
<span id="cb110-6"><a href="estadística-descriptiva.html#cb110-6"></a><span class="st"> </span><span class="kw">geom_point</span>(<span class="dt">colour =</span> <span class="st">&quot;#0c4c8a&quot;</span>) <span class="op">+</span></span>
<span id="cb110-7"><a href="estadística-descriptiva.html#cb110-7"></a><span class="st"> </span><span class="kw">theme_minimal</span>()</span></code></pre></div>
<p><img src="tecnicas-cuantitativas_files/figure-html/unnamed-chunk-47-1.png" width="672" /></p>
<p>O representaciones más modernas como con la librería <code>corrplot</code>:</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="estadística-descriptiva.html#cb111-1"></a><span class="co"># improved correlation matrix</span></span>
<span id="cb111-2"><a href="estadística-descriptiva.html#cb111-2"></a><span class="kw">library</span>(corrplot)</span>
<span id="cb111-3"><a href="estadística-descriptiva.html#cb111-3"></a></span>
<span id="cb111-4"><a href="estadística-descriptiva.html#cb111-4"></a><span class="kw">corrplot</span>(<span class="kw">cor</span>(dat),</span>
<span id="cb111-5"><a href="estadística-descriptiva.html#cb111-5"></a>         <span class="dt">method =</span> <span class="st">&quot;number&quot;</span>,</span>
<span id="cb111-6"><a href="estadística-descriptiva.html#cb111-6"></a>         <span class="dt">type =</span> <span class="st">&quot;upper&quot;</span> <span class="co"># show only upper side</span></span>
<span id="cb111-7"><a href="estadística-descriptiva.html#cb111-7"></a>         )</span></code></pre></div>
<p><img src="tecnicas-cuantitativas_files/figure-html/unnamed-chunk-48-1.png" width="672" /></p>
</div>
</div>
<div id="ejercicios-1" class="section level2">
<h2><span class="header-section-number">2.4</span> Ejercicios</h2>
<ol style="list-style-type: decimal">
<li>Estableced en clase un debate sobre variables de carácter territorial que consideréis que pueden estar correlacionadas y en qué medida.</li>
</ol>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>Es importante recordar que probamos una relación <em>lineal</em> entre las dos variables ya que usamos la correlación de Pearson. Puede darse el caso de que exista una relación entre las dos variables en la población, pero esta relación puede no ser lineal.<a href="estadística-descriptiva.html#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="intro.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="estadística-inferencial.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["tecnicas-cuantitativas.pdf", "tecnicas-cuantitativas.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
